-- =============================================================================
-- Migration: 0189_cb_og_figures.sql
-- Wire 95 cropped figure images (graphs / geometry / charts) into the
-- CB OG #1–#10 questions seeded by 0164–0173. Images are served from
-- viewer/public/data/tests/cb-og-N/figures/mM-qN.png (committed to the repo,
-- deployed by Cloudflare Pages). Sets test_questions.figure + passage_alt (the
-- figure description, also the a11y alt text) and resets passage to the clean
-- original (the seed had folded the description into passage while there was no
-- image). Tables stay as text in passage (not touched here). Idempotent.
-- =============================================================================

UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m3-q11.png', passage_alt='Scatterplot in the first quadrant. The x-axis runs from 0 to 8 (gridlines at 1,2,3,4,5,6,7,8) and the y-axis runs from 0 to 10 (gridlines at 1 through 10). Plotted data points form a positive linear trend rising from lower-left to upper-right: points are located approximately at (1,0), (1.5,1), (2,2), (2.5,3), (3,4), (3.5,4), (4,6), (4.5,7), (5,7), (5.5,8), (6,9), (6.5,10). The points trend upward with positive slope.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=3 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m3-q12.png', passage_alt='Graph of a cubic curve y = f(x) on an xy-plane. The x-axis is labeled from about -8 to 8 and the y-axis from about -16 to 16 (gridlines every 2 units). The curve comes down steeply from the upper-left, crosses the x-axis once on the negative side (near x = -3), continues down to a local minimum, rises to cross the x-axis (near x = -1), reaches a local maximum, falls again to cross the x-axis a third time (near x = 2), then rises steeply to the upper-right. The curve intersects the x-axis at three distinct points.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=3 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m3-q18.png', passage_alt='Line graph in the first quadrant. The horizontal axis is labeled ''Company A'' and runs from 0 to 100 (gridlines at 10,20,30,40,50,60,70,80,90,100). The vertical axis is labeled ''Company B'' and runs from 0 to 50 (gridlines at 10,20,30,40,50). A straight line segment with negative slope is drawn, beginning at the y-intercept (0, 40) and decreasing to the x-intercept (60, 0).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=3 AND tq.number=18;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m4-q5.png', passage_alt='A right triangle with the right angle at the bottom-left vertex. The vertical left leg is labeled $a$, the horizontal bottom leg is labeled $b$, and the hypotenuse (from the top vertex down to the bottom-right vertex) is labeled $c$. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=4 AND tq.number=5;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m4-q7.png', passage_alt='An xy-plane with the x-axis labeled from 0 to 12 (gridlines at 2, 4, 6, 8, 10, 12) and the y-axis labeled with values -2, 2, 4, 6, 8, 10. A U-shaped upward-opening parabola is drawn. Its vertex sits on the x-axis at approximately x = 7, y = 0 (the single x-intercept). The curve passes through approximately (6, 3) and (8, 3) and rises steeply to y = 10 near x = 5 and x = 9.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=4 AND tq.number=7;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-1/figures/m4-q13.png', passage_alt='Two parallel horizontal lines, the upper labeled $s$ and the lower labeled $t$, are crossed by a transversal line $c$ that slants from lower-left to upper-right. At the intersection of line $c$ with line $s$, the angle is labeled $x^\circ$. At the intersection of line $c$ with line $t$, an angle of $110^\circ$ is marked (interior, on the left/lower side). Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-1' AND tm.position=4 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m1-q14.png', passage_alt='Bar graph titled "Average Number of Individuals Reporting Directly to CEOs." The y-axis is "Average number of individuals directly reporting to CEO" (scale 0 to 7). The x-axis is "Years" with three periods: 1991–1995, 1996–2001, 2001–2008. Two bars per period: managers and department leaders. 1991–1995: managers 2.0, department leaders 3.3. 1996–2001: managers 2.5, department leaders 4.0. 2001–2008: managers 3.0, department leaders 6.8.', passage='Bar graph titled "Average Number of Individuals Reporting Directly to CEOs." The y-axis is "Average number of individuals directly reporting to CEO" (scale 0 to 7). The x-axis shows three time periods. Two bars per period: managers and department leaders. 1991–1995: managers 2.0, department leaders 3.3. 1996–2001: managers 2.5, department leaders 4.0. 2001–2008: managers 3.0, department leaders 6.8.

Considering a large sample of companies, economics experts Marisa Guadalupe, Julie Wulf, and Raghuram Rajan assessed the number of managers and leaders from different departments who reported directly to a chief executive officer (CEO). According to the researchers, the findings suggest that across the years analyzed, there was a growing interest among CEOs in connecting with more departments in their companies.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=1 AND tq.number=14;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m2-q10.png', passage_alt='Bar graph: Voters'' Political Orientation, Level of Political Information, and Probability of Voting. Y-axis Probability of voting (%) 0–100; X-axis Voters'' political orientation (1 = strong Democrat/liberal, 4 = independent, 7 = strong Republican/conservative), values 1–7. Two series: low information, high information.', passage='[Figure: bar graph titled "Voters'' Political Orientation, Level of Political Information, and Probability of Voting." Y-axis: Probability of voting (%), 0 to 100. X-axis: Voters'' political orientation (1 = strong Democrat/liberal, 4 = independent, 7 = strong Republican/conservative), categories 1 through 7. Two series: low information, high information.]

Economists Kerwin Kofi Charles and Melvin Stephens Jr. investigated a variety of factors that influence voter turnout in the United States. Using survey data that revealed whether respondents voted in national elections and how knowledgeable respondents are about politics, Charles and Stephens claim that the likelihood of voting is driven in part by potential voters'' confidence in their assessments of candidates—essentially, the more informed voters are about politics, the more confident they are at evaluating whether candidates share their views, and thus the more likely they are to vote.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=2 AND tq.number=10;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m2-q11.png', passage_alt='Bar graph: Spider Population Count. Y-axis Spider count 0–90; X-axis Day of experiment values 1, 10, 20, 30. Two series: no lizards, with lizards.', passage='[Figure: bar graph titled "Spider Population Count." Y-axis: Spider count, 0 to 90. X-axis: Day of experiment, values 1, 10, 20, 30. Two series: no lizards, with lizards.]

To investigate the effect of lizard predation on spider populations, a student in a biology class placed spiders in two enclosures, one with lizards and one without, and tracked the number of spiders in the enclosures for 30 days. The student concluded that the reduction in the spider population count in the enclosure with lizards by day 30 was entirely attributable to the presence of the lizards.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=2 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m2-q16.png', passage_alt='Bar graph: Power Conversion Efficiency of Lowest and Highest Performing Spin-coated and Spray-coated Electron Transport Layers. Y-axis Power conversion efficiency (%) 0–16; X-axis Thickness, categories lower performing and higher performing. Two series: spray coating, spin coating.', passage='[Figure: bar graph titled "Power Conversion Efficiency of Lowest and Highest Performing Spin-coated and Spray-coated Electron Transport Layers." Y-axis: Power conversion efficiency (%), 0 to 16. X-axis: Thickness, categories "lower performing" and "higher performing." Two series: spray coating, spin coating.]

Perovskite solar cells convert light into electricity more efficiently than earlier kinds of solar cells, and manufacturing advances have recently made them commercially attractive. One bottleneck in the cells, however, has to do with their electron transport layer (ETL), through which absorbed electrons must pass. Often the ETL is applied through a process called spin coating, but such ETLs are fairly inefficient at converting input power to output power. André Taylor and colleagues tested a novel spray coating method for applying the ETL. The team produced ETLs of various thicknesses and concluded that spray coating holds promise for improving the power conversion efficiency of ETLs in perovskite solar cells.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=2 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m3-q1.png', passage_alt='Line graph titled with x-axis labeled "Model year" showing years 2010 through 2019, and y-axis labeled "Percent of cars for sale" with gridlines at 0%, 5%, 10%, 15%. The plotted points are approximately: 2010 = 12%, 2011 = 12%, 2012 = 12%, 2013 = 8%, 2014 = 4% (the lowest point), 2015 = 9%, 2016 = 10%, 2017 = 10%, 2018 = 11%, 2019 = 11%. Consecutive points are connected by line segments.', passage='The line graph shows the percent of cars for sale at a used car lot on a given day by model year.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=3 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m3-q3.png', passage_alt='Two vertical parallel lines labeled m (left) and n (right). A transversal line t slants downward from upper-left to lower-right, crossing line m and then line n. At the intersection of t with line m, the angle labeled x° is marked (on the left side, below the transversal). At the intersection of t with line n, an angle of 33° is marked (to the right, above where t exits below line n). Note: Figure not drawn to scale.', passage='Note: Figure not drawn to scale.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=3 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m3-q4.png', passage_alt='An xy-plane with both axes labeled and a grid. The x-axis is marked from -10 to 10 and the y-axis is marked from 2 to 14 (gridlines at 2, 4, 6, 8, 10, 12, 14). An increasing exponential-type curve is shown: it is nearly flat near y = 6 for large negative x, passes through the y-axis at the point (0, 8), and rises steeply upward to the right, exceeding y = 14 near x = 4.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=3 AND tq.number=4;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m3-q17.png', passage_alt='A circle with center O. Two diameters are drawn through O: diameter PR and diameter QS, dividing the circle into four arcs. Points P, Q, R, S are on the circle (P near top, R near bottom, Q and S on the sides), so that arcs PQ, QR, RS, and SP are formed. Note: Figure not drawn to scale.', passage='Note: Figure not drawn to scale.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=3 AND tq.number=17;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m3-q24.png', passage_alt='An xy-plane with both axes labeled and a grid. The x-axis runs from -10 to 10 and the y-axis from -10 to 10 (gridlines every 2 units). A straight line with a small negative slope is drawn, crossing the y-axis at about (0, 3) and passing through approximately (-8, 5) and (8, 1); it slopes gently downward from upper-left to lower-right (slope = -1/4).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=3 AND tq.number=24;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m4-q3.png', passage_alt='A scatterplot in the xy-plane. The x-axis is labeled x and ranges from about 0 to 8 in increments of 1. The y-axis is labeled y and ranges from 0 to 16 in increments of 2. Data points rise from lower-left to upper-right, and a straight line of best fit with positive slope is drawn through them, crossing roughly y = 2.8 at x = 0 and rising to about y = 16 near x = 8.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=4 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m4-q4.png', passage_alt='The graph of y = f(x) in the xy-plane. Both axes range from -8 to 8. The curve has two branches: a lower-left branch passing through the upper-left increasing region and crossing the y-axis at about y = 3, rising steeply for positive x; and a separate branch in the lower-right region for positive x that increases steeply from negative y values.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=4 AND tq.number=4;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-2/figures/m4-q26.png', passage_alt='Two histograms side by side titled Data Set A and Data Set B. Both have a vertical axis labeled Frequency ranging 0 to 12 in increments of 2, and a horizontal axis labeled Integer with interval marks at 10, 20, 30, 40, 50, 60. Each represents 23 integers grouped into intervals [10,20), [20,30), and so on. The two distributions differ in shape across the intervals.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-2' AND tm.position=4 AND tq.number=26;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m1-q14.png', passage_alt='Bar graph titled “Percentage of Ondo State Small-Scale Farmers Who Are Female, by Main Crop Grown.” Y-axis: Female farmers as a percentage of total (0–60). X-axis (Ondo State region): north Ondo, central Ondo, south Ondo. Legend (bars per region): cereals, root crops, non–root vegetables.', passage='Geographer Adebayo Oluwole Eludoyin and his colleagues surveyed small-scale farmers in three locations in Ondo State, Nigeria—which has mountainous terrain in the north, an urbanized center, and coastal terrain in the south—to learn more about their practices, like the types of crops they mainly cultivated. In some regions, female farmers were found to be especially prominent in the cultivation of specific types of crops and even constituted the majority of farmers who cultivated those crops; for instance, ______

[Bar graph — Percentage of Ondo State Small-Scale Farmers Who Are Female, by Main Crop Grown. Y-axis: Female farmers as a percentage of total (0 to 60). X-axis: Ondo State region (north Ondo, central Ondo, south Ondo). Legend: cereals, root crops, non–root vegetables.]'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=1 AND tq.number=14;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m3-q4.png', passage_alt='A transversal line labeled ℓ crosses two parallel vertical lines labeled m and n (m on the left, n on the right), descending from upper-left to lower-right. The angle the transversal makes at line m, above the transversal and to the right, is labeled x°. The angle the transversal makes at line n, below the transversal, is labeled 26°. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=3 AND tq.number=4;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m3-q7.png', passage_alt='A vertical bar graph titled with y-axis "Number of cans" (gridlines at 0, 10, 20, 30, 40, 50, 60, 70) and x-axis "Group" (groups 1 through 10). Approximate bar heights: group 1 ≈ 30, group 2 ≈ 63, group 3 ≈ 38, group 4 ≈ 50, group 5 ≈ 47, group 6 ≈ 40, group 7 ≈ 54, group 8 ≈ 60, group 9 ≈ 17, group 10 ≈ 20.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=3 AND tq.number=7;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m3-q9.png', passage_alt='A line graph in the first quadrant with a vertical axis labeled y and a horizontal axis labeled x, origin labeled O. A single straight line rises from a positive y-intercept on the y-axis upward to the right at a constant slope (showing a onetime fee plus an hourly rate). No numeric scale shown.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=3 AND tq.number=9;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m3-q24.png', passage_alt='An xy-coordinate grid with x-axis from about -10 to 0 and y-axis from about 0 down to -10 (y-axis labeled at top, x-axis to the right, origin O at upper right). A curve enters near (-10, -0.7), stays close to the x-axis on the left, then curves sharply downward as x increases, dropping steeply near x = -4 toward y = -10. The curve approaches a vertical asymptote around x = -4.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=3 AND tq.number=24;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m4-q2.png', passage_alt='An exponential-type curve is plotted in the xy-plane on a grid with both axes labeled from about -5 to 10. The curve rises steeply from left to right, crossing the y-axis at the point (0, 2).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=4 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m4-q11.png', passage_alt='A scatterplot in the first quadrant with the x-axis labeled from 0 to 14 and the y-axis labeled from 0 to about 15. Several data points are scattered with an overall decreasing trend. A line of best fit is drawn that starts near (0, 13.5) and slopes downward to the right with a negative slope of about -0.8, passing near (14, 2).', passage='The scatterplot shows the relationship between two variables, $x$ and $y$. A line of best fit is also shown.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=4 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-3/figures/m4-q24.png', passage_alt='Two dot plots side by side, labeled Data Set A and Data Set B, sharing a horizontal value axis labeled from 10 through 18. Each dot plot shows the frequency distribution of values as stacked dots above the value axis; the two distributions appear similar in spread and center.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-3' AND tm.position=4 AND tq.number=24;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m1-q13.png', passage_alt='Bar graph: US States with the Greatest Number of Organic Farms in 2016. Vertical axis: Number of organic farms (0 to 2,800 by 200). Bars for several US states (e.g., California, Wisconsin, New York, Pennsylvania, Iowa, Washington).', passage='Bar graph titled "US States with the Greatest Number of Organic Farms in 2016." The horizontal axis lists states; the vertical axis is "Number of organic farms" ranging from 0 to 2,800 in increments of 200. Approximate values: California about 2,700; Wisconsin about 1,300; New York about 1,000; Pennsylvania about 800; Iowa about 700; Washington about 700.

Organic farming is a method of growing food that tries to reduce environmental harm by using natural forms of pest control and avoiding fertilizers made with synthetic materials. Organic farms are still a small fraction of the total farms in the United States, but they have been becoming more popular. According to the US Department of Agriculture, in 2016 California had between 2,600 and 2,800 organic farms and ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=1 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m2-q13.png', passage_alt='Line graph: Economic Policy Uncertainty in the United Kingdom, 2005–2010. X-axis: Year (2005–2010). Y-axis: Uncertainty (larger values = more uncertainty), 0–200. Three lines: tax and public spending policy; trade policy; general economic policy.', passage='Figure (line graph) titled "Economic Policy Uncertainty in the United Kingdom, 2005–2010": x-axis = Year (2005, 2006, 2007, 2008, 2009, 2010); y-axis = Uncertainty (larger values = more uncertainty), scaled 0, 50, 100, 150, 200. Three lines are plotted: tax and public spending policy, trade policy, and general economic policy.

High levels of public uncertainty about which economic policies a country will adopt can make planning difficult for businesses, but measures of such uncertainty have not tended to be very detailed. Recently, however, economist Sandile Hlatshwayo analyzed trends in news reports to derive measures not only for general economic policy uncertainty but also for uncertainty related to specific areas of economic policy, like tax or trade policy. One revelation of her work is that a general measure may not fully reflect uncertainty about specific areas of policy, as in the case of the United Kingdom, where general economic policy uncertainty ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=2 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m3-q1.png', passage_alt='Bar graph titled with vertical axis ''Number of students'' (gridlines from 0 to 50 in increments of 5) and horizontal axis ''Activity'' (values 1 through 5). Approximate bar heights: activity 1 = 29, activity 2 = 31, activity 3 = 39, activity 4 = 43, activity 5 = 48.', passage='A group of students voted on five after-school activities. The bar graph shows the number of students who voted for each of the five activities.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=3 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m3-q9.png', passage_alt='Two right triangles are shown. The larger triangle is labeled with vertices P (bottom left), Q (top), and R (bottom right), with the right angle at R. The smaller similar triangle is labeled with vertices S, T, and U. Note: Figures not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=3 AND tq.number=9;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m3-q10.png', passage_alt='A scatterplot with horizontal axis $x$ and vertical axis $y$, both gridded from 1 to 10. Plotted data points show a positive linear association, with $y$ increasing as $x$ increases.', passage='The scatterplot shows the relationship between two variables, $x$ and $y$.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=3 AND tq.number=10;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m3-q12.png', passage_alt='The xy-plane shows a straight line on a grid with both axes labeled from about -10 to 16. The line slopes downward from left to right (negative slope), crossing the y-axis at -8.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=3 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m4-q1.png', passage_alt='A line graph titled with x-axis labeled "Year" showing years 1989 through 1999, and y-axis labeled "Estimated number of chipmunks" ranging from 0 to 200 in increments of 50. The plotted line: starts near 40 in 1989, stays near 40 in 1990, rises to about 100 in 1991, stays at about 100 in 1992, drops to about 50 in 1993, peaks at about 160 in 1994, drops to about 50 in 1995, rises to about 100 in 1996, stays near 100 in 1997, drops to about 50 in 1998, and rises to about 110 in 1999.', passage='The line graph shows the estimated number of chipmunks in a state park on April 1 of each year from 1989 to 1999.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=4 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m4-q16.png', passage_alt='A transversal line labeled t crosses two parallel horizontal lines, the upper labeled m and the lower labeled n. At the intersection of t with line m, an angle x degrees is marked above the line and an angle y degrees is marked below the line (adjacent angles). At the intersection of t with line n, an angle z degrees is marked. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=4 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m4-q22.png', passage_alt='A coordinate grid in the xy-plane with both axes ranging from about -10 to 10. Two straight lines are graphed, representing a system of two linear equations that intersect at a single point.', passage='A system of equations is shown by two lines graphed in the xy-plane.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=4 AND tq.number=22;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-4/figures/m4-q24.png', passage_alt='A dot plot titled "Data Set A" over a number line labeled 22, 23, 24, 25, 26. Dots are stacked above the values to represent the 15 data points in data set A.', passage='The dot plot, titled "Data Set A," represents the 15 values in data set A along a number line marked 22, 23, 24, 25, 26.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-4' AND tm.position=4 AND tq.number=24;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m1-q16.png', passage_alt='Line graph titled “Ratio of Manganese to Calcium in Samples from Alboran Sea and Mauritanian Coast.” X-axis: Approximate years before present (in thousands), values 2 to 20. Y-axis: manganese-to-calcium ratio, values 0 to 100. Two plotted series: Alboran Sea and Mauritanian coast.', passage='Ratio of Manganese to Calcium in Samples from Alboran Sea and Mauritanian Coast
[Line graph. X-axis: Approximate years before present (in thousands), from 2 to 20. Y-axis: Manganese to calcium ratio (arbitrary units), from 0 to 100. Two series are plotted: Alboran Sea and Mauritanian coast.]

The population of the coral Lophelia pertusa declined significantly around 9,000 years ago in the Alboran Sea and around 11,000 years ago near the Mauritanian coast. Using the ratio of manganese to calcium, which inversely correlates with ocean oxygenation levels, marine scientist Rodrigo da Costa Portilho-Ramos and colleagues evaluated whether oxygenation played a role in the declines of L. pertusa. The researchers concluded that oxygenation may have been important in the Alboran Sea but not near the Mauritanian coast, since ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=1 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m2-q12.png', passage_alt='Line graph titled "Total Science Research Submissions by Topic, 2016–2019"; y-axis Number of submissions (0–350), x-axis Year (2016–2019); four series: cellular and molecular biology, physics and space science, medicine and health, animal science.', passage='Total Science Research Submissions by Topic, 2016–2019. A line graph shows the number of submissions (y-axis, 0 to 350) by year (x-axis, 2016 to 2019) for four topics: cellular and molecular biology, physics and space science, medicine and health, and animal science.

A student is researching the trends in the topics submitted to a national science fair for high school students. The graph shows the number of submissions by topic that were made each year. Based on the data in the graph, the student claims that there were more medicine and health research topics submitted in 2019 than in any other year.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=2 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m2-q14.png', passage_alt='Bar graph titled "Modeled Radial Growth of Sugar Maple Trees"; y-axis Radial growth (millimeters per year), 0–0.25; x-axis Climate scenario (current climate, moderate change, extreme change); two bars per scenario: with nitrogen and without nitrogen.', passage='Modeled Radial Growth of Sugar Maple Trees. A bar graph shows radial growth (y-axis, in mm, 0 to 0.25) under three climate scenarios (current climate, moderate change, extreme change), each with two bars: with nitrogen and without nitrogen.

Inés Ibáñez and colleagues studied a forest site in which some sugar maple trees receive periodic fertilization with nitrogen to mimic the broader trend of increasing anthropogenic nitrogen deposition in soil. Ibáñez and colleagues modeled the radial growth of the trees with and without nitrogen fertilization under three different climate scenarios (the current climate, moderate change, and extreme change). Although they found that climate change would negatively affect growth, they concluded that anthropogenic nitrogen deposition could more than offset that effect provided that change is moderate rather than extreme.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=2 AND tq.number=14;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q1.png', passage_alt='An xy-plane with grid, x-axis labeled from -2 to 9 and y-axis labeled from -2 to 9, origin O. A curved (nonlinear) graph starts at about (-2, 4), is nearly horizontal near y = 4, then curves upward to the right passing through about (5, 5) and rising steeply. A straight line passes from upper left, descending steeply through about (3, 9) down through (4, 5) and continuing to about (5, -2). The two graphs intersect at the point (4, 5).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q3.png', passage_alt='An xy-plane with grid, x-axis labeled from -2 to 14 (by 2s) and y-axis labeled from -1 to 8, origin O. A straight line with negative slope passes through about (0, 8) on the y-axis and descends to the right, crossing the x-axis at about x = 5.5 and continuing downward to about (7, -1).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q6.png', passage_alt='An xy-plane with grid, x-axis labeled from -1 to 9 and y-axis labeled from -2 to 5, origin O. Two straight lines are shown. One line has positive slope rising from lower left (about (2, -2)) up to the right through about (6, 5). The other line has negative slope descending from upper left (about (2, 5)) down to the right through about (6, -2). The two lines intersect at about (4, 1).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=6;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q8.png', passage_alt='A transversal line k crosses two parallel lines m and n (m above n). Line k descends from upper right to lower left, crossing line m and then line n. At the intersection of line k with line m, an angle of 145° is marked (interior, to the lower-left of the intersection). An angle x° is associated with the intersection at line n. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=8;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q16.png', passage_alt='The given graph: an xy-plane with grid, x-axis labeled to 10 (by 2s) and y-axis labeled from -4 to 12 (by 2s), origin O. The curve of f starts very high near (0, 12), drops steeply, passing through about (2, 3), and decreases gradually approaching a horizontal asymptote at about y = 1 for large x (x >= 0). Answer choices A-D each show an xy-plane with the same axes (x to 10, y from -4 to 12), showing different downward-curving rational graphs with different horizontal asymptotes: A approaches about y = -4, B approaches about y = 0, C approaches about y = 1, D approaches about y = 6.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m3-q20.png', passage_alt='A right triangle. The right angle is at the bottom-left vertex. The vertical left leg has length 11. The hypotenuse, going from the top vertex down to the bottom-right vertex, has length 28. The angle x° is marked at the top vertex (between the vertical leg of length 11 and the hypotenuse of length 28). Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=3 AND tq.number=20;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m4-q2.png', passage_alt='Line graph in the xy-plane. The horizontal axis is labeled "Temperature (kelvins)" with gridlines at 100, 200, 300, 400, 500, 600, 700, and 800. The vertical axis is labeled $y$ with marked values 6, 12, 18, 24, 30, and 36 (pressure in psi). A straight line rises from near the origin, passing through approximately (100, 6) and (200, 12), increasing steadily so that at $x = 600$ the line is at $y = 36$.', passage='Argon is placed inside a container with a constant volume. The graph shows the estimated pressure $y$, in pounds per square inch (psi), of the argon when its temperature is $x$ kelvins.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=4 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m4-q9.png', passage_alt='Curve in the xy-plane. The horizontal axis is labeled "Time (seconds)" with gridlines at 1, 2, and 3; the vertical axis is labeled "Height (meters)" with $y$ marked at 3, 6, 9, and 12. The curve starts at about (0, 10), rises slightly to a maximum near 10 meters at about $x = 0.2$, then curves downward and decreases, crossing the x-axis (height 0) at about $x = 1.6$ seconds.', passage='A competitive diver dives from a platform into the water. The graph shown gives the height above the water $y$, in meters, of the diver $x$ seconds after diving from the platform.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=4 AND tq.number=9;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-5/figures/m4-q11.png', passage_alt='Scatterplot in the first quadrant. Both axes range from about 1 to 10, with the vertical axis labeled $y$ and the horizontal axis labeled $x$. Ten data points are plotted in a generally increasing pattern, and a straight upward-sloping line of best fit passes through the cluster of points. Some points lie above the line and some below it; the question asks how many points lie above the line of best fit.', passage='The scatterplot shows the relationship between two variables $x$ and $y$. A line of best fit for the data is also shown.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-5' AND tm.position=4 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m1-q14.png', passage_alt='Bar graph titled "Mean Attentiveness Scores by Leave Time Condition." Y-axis: Mean test score (higher scores indicate greater attentiveness), 0 to 600. X-axis: Test administration (first, second, third). Three series: no leave, 2–4 days leave, 1–5 weeks leave.', passage='Mean Attentiveness Scores by Leave Time Condition
The graph plots mean test score (higher scores indicate greater attentiveness) on the y-axis (0 to 600) against test administration (first, second, third) on the x-axis, with three series: no leave, 2–4 days leave, and 1–5 weeks leave.

To investigate potential cognitive benefits of taking leave from work, psychologist Jan Packer and colleagues conducted a six-month study of Australian university staff members who took no leave from work during the study, took 2–4 days of leave, or took 1–5 weeks of leave. Tests of attentiveness were administered to participants three times during the study: at random for the no-leave staff, and for the rest, one week before their leave, one week following their return to work, and one week after the second test administration. After analyzing the results, the researchers concluded that longer leave times might not confer a greater cognitive benefit than shorter leave times do.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=1 AND tq.number=14;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m1-q15.png', passage_alt='Bar graph titled "Number of Lizard Species by Average Percent of Maximal Speed Used When Pursuing Prey or Escaping Predators." Y-axis: Number of lizard species (0 to 9). X-axis: Percent of maximal speed. Two series: escaping and pursuing.', passage='Number of Lizard Species by Average Percent of Maximal Speed Used When Pursuing Prey or Escaping Predators
The graph plots number of lizard species (y-axis, 0 to 9) against percent of maximal speed (x-axis) for two series: escaping and pursuing.

It may seem that the optimal strategy for an animal pursuing prey or escaping predators is to move at maximal speed, but the energy expense of exploiting full speed capacity can disfavor such a strategy even in escape contexts, as evidenced by the fact that ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=1 AND tq.number=15;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m2-q13.png', passage_alt='Line graph titled "Recreation Visits by Month to Four US National Parks during the Peak Season in 2021." X-axis: months June, July, August. Y-axis: number of recreation visits (in thousands), 0 to 1,100. Four lines: Yellowstone, Zion, Grand Canyon, Rocky Mountain.', passage='Recreation Visits by Month to Four US National Parks during the Peak Season in 2021. [Line graph: x-axis shows three months (June, July, August); y-axis shows number of recreation visits in thousands, from 0 to 1,100. Four lines plotted: Yellowstone, Zion, Grand Canyon, and Rocky Mountain.]

In 2021, four of the United States national parks that were among the most visited were Grand Canyon National Park, Rocky Mountain National Park, Yellowstone National Park, and Zion National Park. The graph shows the number of visits for recreation to each of these parks during the three-month period with the highest number of visitors. A student notes that among the parks shown in the graph, the park with the highest monthly recreation visits in all three months was ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=2 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q2.png', passage_alt='Scatterplot in the xy-plane. The horizontal x-axis is labeled from 1 to 7 and the vertical y-axis is labeled 1,000 to 5,000 in increments of 1,000, origin O. Data points rise with a concave-up (exponential-like) pattern: points near (0.3, 100), (2, 250), (3, 250), (3.5, 900), (4, 800), (5, 2200), (5.5, 2600), and (6.5, 4800). Each answer choice A-D overlays the same scatterplot with a different candidate model curve.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q5.png', passage_alt='Graph in the xy-plane. The horizontal axis is labeled "Time (seconds)" with gridlines from 1 to 10; the vertical axis is labeled "Height above ground (meters)" with gridlines at 10, 20, 30, 40, 50, 60. The curve starts above the origin, rises to a maximum height of about 60 meters near x = 3, then decreases, crossing the x-axis near x = 9 (a concave-down parabola-like flight path).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=5;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q14.png', passage_alt='A right triangle with the right angle at the bottom-left vertex. The vertical leg on the left is labeled 3 and the horizontal leg along the bottom is labeled 5. The hypotenuse runs from the top of the vertical leg down to the right end of the horizontal leg. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=14;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q15.png', passage_alt='Graph in the xy-plane. The horizontal x-axis is labeled 1 to 6 and the vertical y-axis is labeled in unit increments from 1 to 13. A smooth concave-down curve begins at about (0, 5), rises through the points, and levels off near a maximum of about 13 around x = 4 to 5.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=15;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q21.png', passage_alt='Graph in the xy-plane with x-axis labeled -6, -4, -2, 2, 4 and y-axis labeled 4, 2, -2, -4, -6, -8, -10, origin O. An upward-opening parabola has its vertex near (-1.5, -8) and passes through the points (-2, -6) and (0, -6); it crosses the x-axis near x = -3.5 and x = 0.5.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=21;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q23.png', passage_alt='Graph in the xy-plane with x-axis labeled -6, -4, -2, 2 and y-axis labeled -6, -4, -2, 2, 4, 6, origin O. Circle A is drawn centered at (-2, 0) with radius 3 (a dot marks the center).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=23;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m3-q24.png', passage_alt='Right triangle ABC with the right angle at vertex C (bottom-left). Vertex A is at the top-left, vertex B at the bottom-right. The hypotenuse AB is labeled 54, and the angle at B is labeled 30 degrees. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=3 AND tq.number=24;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m4-q2.png', passage_alt='Two straight lines cross at a single point, forming an X. Angle 1 and angle 2 are the pair of vertical (opposite) angles formed at the intersection.', passage='Note: Figure not drawn to scale.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=4 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m4-q4.png', passage_alt='An xy-coordinate plane with gridlines, x-axis from about -10 to 10 and y-axis from about -10 to 10. A single straight line is graphed that falls from upper-left to lower-right, crossing the axes (a line with negative slope).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=4 AND tq.number=4;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m4-q5.png', passage_alt='An xy-coordinate plane with origin O. The x-axis is marked at 2 and 4; the y-axis is marked at -2, -4, -6, -8. A straight line with positive slope rises from lower-left to upper-right, crossing the y-axis below the origin (between 0 and -4) and crossing the x-axis at a positive x-value.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=4 AND tq.number=5;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-6/figures/m4-q26.png', passage_alt='A scatterplot on an xy-plane. The x-axis is marked at 4, 8, 12, 16, 20; the y-axis is marked at 10, 20, 30, 40, 50. Several data points rise from lower-left (around x=2, y=14) to upper-right (around x=18, y=40), with an increasing straight line of best fit drawn through them; the line appears to cross the y-axis near y=12.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-6' AND tm.position=4 AND tq.number=26;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m1-q12.png', passage_alt='Bar graph: “Percentage of Participants Who Mentioned Factors.” X-axis “Factor” with bars for convenience, costs, and established behaviors; Y-axis “Percent” 0–80.', passage='[Bar graph titled “Percentage of Participants Who Mentioned Factors.” The horizontal axis is labeled “Factor” and shows three factors: convenience, costs, and established behaviors. The vertical axis is labeled “Percent” and ranges from 0 to 80. Approximate values: convenience about 95%, costs about 25%, established behaviors about 50%.]

Researcher Judith Hilton and her team interviewed 55 people about which factors would make them switch from using single-use plastic containers to reusable containers. The graph shows three of the factors mentioned in the interviews and the percentage of participants who mentioned them.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=1 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m1-q15.png', passage_alt='Bar graph: “Percentage of ULE Attributed to Population Growth and GDP per Capita Growth in Two World Regions.” Grouped bars (urban population growth, GDP per capita growth) for Region 1 and Region 2 across 1970–2000 and 2000–2014; Y-axis “Percentage attribution” 0–90.', passage='[Bar graph titled “Percentage of ULE Attributed to Population Growth and GDP per Capita Growth in Two World Regions.” The horizontal axis is labeled “Region, time period” and shows four groups: Region 1 (1970–2000), Region 1 (2000–2014), Region 2 (1970–2000), and Region 2 (2000–2014). The vertical axis is labeled “Percentage attribution” and ranges from 0 to 90. Each group has two bars: urban population growth and GDP per capita growth.]

In a study of urban physical expansion, Richa Mahtta et al. conducted a meta-analysis of more than 300 cities worldwide to determine whether urban land expansion (ULE) was more strongly influenced by urban population growth or by growth in gross domestic product (GDP) per capita, a measure of economic activity. Because efficient national government is necessary to provide urban services and infrastructure that attract economic investment, Mahtta et al. propose that absent other factors, the importance of GDP per capita growth to ULE would likely increase relative to the importance of population growth as governments become more efficient. If true, this suggests the possibility that ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=1 AND tq.number=15;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m1-q16.png', passage_alt='Bar graph: “China''s Imports by Type, 2000–2006.” Grouped bars by year (2000, 2003, 2006) for ordinary imports, processing with assembly, and processing with inputs; Y-axis “Imports (in hundreds of millions of dollars)” 0–3,500.', passage='[Bar graph titled “China''s Imports by Type, 2000–2006.” The horizontal axis is labeled “Import types” and shows three categories: ordinary imports, processing with assembly, and processing with inputs. The vertical axis is labeled “Imports (in hundreds of millions of dollars)” and ranges from 0 to 3,500. Each category has three bars for the years 2000, 2003, and 2006.]

A student is researching the Chinese government''s 1992 shift to a market economy that emphasizes trade liberalization. One means of trade liberalization involves expanding from ordinary imports into an emphasis on processing imports, which have two types: processing with assembly (in which a firm obtains raw materials from a foreign trading partner without payment and sells the final goods to that partner, charging for assembly) and processing with inputs (in which a firm expends capital to buy raw materials from a trading partner, processes them into final goods, and sells those goods to whichever trading partner it chooses). The student asserts that while initial efforts at trade liberalization were shaped by Chinese firms'' limited capital, this situation resolved during the 2000s.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=1 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m3-q1.png', passage_alt='Scatterplot with x-axis ''Distance above sea level (feet)'' marked 0, 2,000, 4,000, 6,000, 8,000 and y-axis ''Temperature ($\degree$F)'' marked from 0 to 80 in increments of 10. Six data points are plotted with a downward-sloping line of best fit; at 0 feet the line is near 60$\degree$F and it decreases as distance increases.', passage='The scatterplot shows the temperature, in degrees Fahrenheit ($\degree$F), and the distance above sea level, in feet, measured at 6 locations on Mount Jefferson. A line of best fit is also shown.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=3 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m3-q5.png', passage_alt='Bar graph with x-axis ''Charge (kWh)'' showing categories 0, 8, 9, 11, 16, 23 and y-axis ''Number of days'' marked from 0 to 7. Bars indicate how many days each charge amount occurred.', passage='The bar graph summarizes the charge, in kilowatt-hours (kWh), a battery received each day for 15 days.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=3 AND tq.number=5;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m3-q8.png', passage_alt='Line graph with x-axis ''Number of months after purchase'' marked 0, 4, 8, 12, 16, 20, 24 and y-axis ''Value (dollars)'' marked 50, 100, 150, 200, 250, 300, 350. The line decreases from a y-intercept near 225 at month 0 down toward lower values as months increase.', passage='The graph shown gives the estimated value, in dollars, of a tablet as a function of the number of months since it was purchased.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=3 AND tq.number=8;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m3-q11.png', passage_alt='Graph in the $xy$-plane showing a V-shaped absolute value function and a straight line. The x-axis is marked from $-8$ to $3$ and the y-axis from 1 to 9. The two graphs intersect at a single point near $(-3, 4)$.', passage='The graph of a system of an absolute value function and a linear function is shown.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=3 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m3-q20.png', passage_alt='Scatterplot with x-axis ''Time (minutes)'' marked 0 through 8 and y-axis ''Temperature ($\degree$C)'' marked in increments of 2 from 0 to 30. Data points show recorded temperatures at various times.', passage='During a study, the temperature, in degrees Celsius ($\degree$C), of the air in a chamber was recorded to the nearest integer at certain times. The scatterplot shows the recorded temperature $y$, in $\degree$C, of the air in the chamber $x$ minutes after the start of the study.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=3 AND tq.number=20;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m4-q3.png', passage_alt='An upward-opening parabola on an xy-coordinate plane. The x-axis ranges from about -2 to 2 and the y-axis is labeled from -1 to 12. The curve''s lowest point (vertex) is at (0, 2), and the parabola rises symmetrically on both sides, passing through about (-2, 10) and (2, 10).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=4 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-7/figures/m4-q12.png', passage_alt='A scatterplot on an xy-coordinate plane. The x-axis is labeled from 1 to 7 and the y-axis from 2 to 14 (gridlines every 2 units). About a dozen data points scatter upward from lower left to upper right. A straight line of best fit rises through the points, passing through roughly (0, 1.5) and (7, 14.5), giving a positive slope of approximately 2 (slightly under).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-7' AND tm.position=4 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m3-q3.png', passage_alt='A coordinate plane with the x-axis labeled from -10 to 10 and the y-axis labeled to about 14. An increasing curve rises from the lower left, passing upward through the y-axis. The curve crosses the y-axis at the point (0, 8).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=3 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m3-q11.png', passage_alt='A scatterplot on a coordinate grid with the x-axis labeled from 1 to 10 and the y-axis labeled from 1 to 10 (with 11 marked at top). The plotted points show a decreasing (negative) linear trend: starting near the upper left around (1, 10) and falling to the lower right around (8, 1), with intermediate points roughly at (2, 8), (3, 7), (4, 6), (5, 4), (6, 3).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=3 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m3-q15.png', passage_alt='A coordinate plane with the x-axis labeled from -8 to 8 and the y-axis labeled from about -8 to 16. A cubic curve is shown: it comes up from the lower left, has a local maximum in the second quadrant, dips to a local minimum near the origin region, and then rises again to the upper right. The curve crosses the x-axis at three distinct points.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=3 AND tq.number=15;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m4-q1.png', passage_alt='A coordinate plane with the $x$-axis (gridlines from about $-8$ to $2$) and the $y$-axis (gridlines from about $-2$ to $10$). A straight line with positive slope rises from lower left to upper right, crossing the $y$-axis at a positive value.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=4 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m4-q3.png', passage_alt='Two parallel lines $m$ and $n$ (drawn nearly vertical, sloping) are crossed by a transversal line $t$. An angle of $33°$ is marked where $t$ crosses line $m$, and the angle $x°$ is marked at the intersection of $t$ with line $n$. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=4 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m4-q5.png', passage_alt='A right triangle with the right angle at the bottom-left vertex. The vertical left leg is labeled $a$, the horizontal bottom leg is labeled $b$, and the hypotenuse (rising from bottom-right to top) is labeled $c$. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=4 AND tq.number=5;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m4-q12.png', passage_alt='A right triangle with vertices $B$ (top), $C$ (bottom-left, right angle), and $A$ (bottom-right). The vertical leg $BC$ is labeled $35$, and the hypotenuse $BA$ is labeled $171$. Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=4 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-8/figures/m4-q19.png', passage_alt='Two dot plots labeled "Data Set A" and "Data Set B", each with a number-line axis labeled "Value" marked from 10 to 16. Data Set A''s dots are clustered toward the lower-middle values; Data Set B''s dots are spread more widely across the range. Both distributions appear centered around the same median value.', passage='The dot plots represent the distributions of values in data sets A and B.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-8' AND tm.position=4 AND tq.number=19;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-9/figures/m1-q13.png', passage_alt='Bar graph titled "Metal Content of Plants with and without Kanamycin Exposure." Y-axis: Metal content (parts per million), 0 to 700. X-axis: Experimental condition (without kanamycin, with kanamycin). Bars show iron and zinc levels for each condition (legend: zinc, iron).', passage='Many plants lose their leaf color when exposed to kanamycin, an antibiotic produced by some soil microorganisms. Spelman College biologist Mentewab Ayalew and her colleagues hypothesized that plants'' response to kanamycin exposure involves altering their uptake of metals, such as iron and zinc. The researchers grew two groups of seedlings of the plant Arabidopsis thaliana, half of which were exposed to kanamycin and half of which were a control group without exposure to kanamycin, and measured the plants'' metal content five days after germination.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-9' AND tm.position=1 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-9/figures/m1-q15.png', passage_alt='Bar graph titled "Percentage of Nonhexagonal Cells in Hives of Three Honeybee Species." Y-axis: Average percentage of nonhexagonal cells, 0 to 3.0. X-axis: Species (black dwarf honeybee, dwarf honeybee, western honeybee). Bars grouped by cell type (legend: 5-sided cells, 7-sided cells, 8-sided cells).', passage='Honeybee hives consist mainly of hexagonal (six-sided) units called cells, in which queens lay eggs. Hexagonal cells for eggs that develop into nonreproductive workers are smaller than those for eggs that develop into reproductive drones, though the size difference varies by species. Difference in cell size results in a construction problem—it''s hard to neatly connect sections of small cells to sections of large cells—that worsens as the difference increases. To fill in gaps between the sections when building a hive, bees rely on cells that have more or fewer than six sides. A student studying beehive structure consults data on three species, concluding that ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-9' AND tm.position=1 AND tq.number=15;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-9/figures/m3-q12.png', passage_alt='A circle with center O. Two diameters PR and QS intersect at O, dividing the circle into four arcs. Points P, Q, R, S are on the circle (P top-left, R bottom-right area; Q and S as the other diameter endpoints). Note: Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-9' AND tm.position=3 AND tq.number=12;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-9/figures/m4-q6.png', passage_alt='A transversal line $c$ crosses two parallel horizontal lines, the upper line labeled $s$ and the lower line labeled $t$. At the intersection of $c$ with line $s$, the angle on the upper-left side is labeled $x°$. At the intersection of $c$ with line $t$, an angle of $110°$ is marked. Figure not drawn to scale.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-9' AND tm.position=4 AND tq.number=6;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-9/figures/m4-q17.png', passage_alt='Two dot plots side by side, each plotting number of glue sticks. Class A is plotted over a number line marked 1 2 3 4 5 6 7, with dots clustered in the middle of that range. Class B is plotted over a number line marked 14 15 16 17 18 19 20, with dots clustered in the middle of that range. Both distributions have a similar shape/spread about their respective centers.', passage='Two dot plots represent the number of glue sticks brought in by each student for two classes. Class A: values range across 1 to 7 on its number line. Class B: values range across 14 to 20 on its number line.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-9' AND tm.position=4 AND tq.number=17;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m1-q17.png', passage_alt='Line graph titled "Average Survival of Fruit Flies following Infection." X-axis: "Days after infection" (0, 2, 6, 10, 14). Y-axis: "Survival rate (% alive)" (0 to 110 by 10s). Three series: type A flies (solid line, filled triangles) stays high, declining from 100% to about 90% by day 14; type AB flies (dashed line, open squares) drops from 100% to about 45% at day 6, about 11% at day 10, near 0% at day 14; type B flies (dotted line, open circles) drops from 100% to about 41% at day 6, near 0% by day 10–14.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=1 AND tq.number=17;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m2-q11.png', passage_alt='Bar graph titled "Top Four Species of Wild Land Mammals by Global Biomass." Vertical axis: Global biomass (millions of tonnes), scaled 0 to 3.0. Horizontal axis lists four species: African bush elephant, eastern gray kangaroo, wild boar, and white-tailed deer.', passage='Top Four Species of Wild Land Mammals by Global Biomass [Bar graph. Vertical axis: Global biomass (millions of tonnes), from 0 to 3.0. Horizontal axis lists four species: African bush elephant, eastern gray kangaroo, wild boar, white-tailed deer.]

Global biomass is the total mass of living material, such as animals and plants, on Earth. A team of scientists estimated the global biomass, by species, of various wild land mammals. The team found that the species with the highest global biomass is the ______'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=2 AND tq.number=11;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m2-q13.png', passage_alt='Bar graph titled "Power Conversion Efficiency of Lowest and Highest Performing Spin-coated and Spray-coated Electron Transport Layers." Vertical axis: Power conversion efficiency (%), scaled 0 to 18. Horizontal axis: Thickness, with lowest performing and highest performing groupings. Legend: spray coating and spin coating.', passage='Power Conversion Efficiency of Lowest and Highest Performing Spin-coated and Spray-coated Electron Transport Layers [Bar graph. Vertical axis: Power conversion efficiency (%), from 0 to 18. Horizontal axis: Thickness, grouped as lowest performing and highest performing. Legend: spray coating, spin coating.]

Perovskite solar cells convert light into electricity more efficiently than earlier kinds of solar cells, and manufacturing advances have recently made them commercially attractive. One limitation of the cells, however, has to do with their electron transport layer (ETL), through which absorbed electrons must pass. Often the ETL is applied through a process called spin coating, but such ETLs are fairly inefficient at converting input power to output power. André Taylor and colleagues tested a novel spray coating method for applying the ETL. The team produced ETLs of various thicknesses and concluded that spray coating holds promise for improving the power conversion efficiency of ETLs in perovskite solar cells.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=2 AND tq.number=13;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m3-q1.png', passage_alt='Line graph titled with x-axis "Model year" (labeled 2010 through 2019) and y-axis "Percent of cars for sale" (0% to 15%). The plotted points: 2010 ≈ 12%, 2011 ≈ 12%, 2012 ≈ 12%, 2013 ≈ 8%, 2014 ≈ 4%, 2015 ≈ 9%, 2016 ≈ 10%, 2017 ≈ 10%, 2018 ≈ 11%, 2019 ≈ 11%. The lowest point is at 2014.', passage='The line graph shows the percent of cars for sale at a used car lot on a given day by model year.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=3 AND tq.number=1;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m3-q2.png', passage_alt='An xy-coordinate plane with x-axis from -6 to 6 and y-axis from -6 to 6. Two straight lines are drawn. The lines intersect at the point (4, -5) in the fourth quadrant.', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=3 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m3-q4.png', passage_alt='The given graph is an upward-opening parabola in an xy-plane (x-axis from -6 to 10, y-axis from -8 to 4) with vertex at approximately (2, -2), passing through the y-axis near y = 4. The four answer choices A-D are each graphs of upward-opening parabolas on identical grids; the correct one is the original parabola shifted up 4 units (vertex near (2, 2)).', passage=NULL
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=3 AND tq.number=4;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m4-q2.png', passage_alt='A scatterplot in the xy-plane. The x-axis is labeled x and runs from 0 to about 14 (gridlines at 2, 4, 6, 8, 10, 12, 14); the y-axis is labeled y and runs from 0 to 20 (gridlines at 2, 4, 6, ..., 20). Five data points rise from lower left to upper right at approximately (4, 6), (6, 10), (8, 11), (10, 13.5), and (12, 15), with a sixth near (13, 16). A straight line of best fit is drawn through them, crossing the y-axis near 3.4 and increasing with a slope of about 1.', passage='The scatterplot shows the relationship between two variables, $x$ and $y$. A line of best fit is also shown.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=4 AND tq.number=2;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m4-q3.png', passage_alt='A line graph in the xy-plane. The x-axis runs from -8 to 8 and the y-axis from -6 to 10. A straight line slopes upward from lower left to upper right, passing through approximately (0, -5) on the y-axis and (2.5, 0) on the x-axis, with a slope of about 2.', passage='The graph shows the linear relationship between $x$ and $y$.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=4 AND tq.number=3;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m4-q16.png', passage_alt='A line graph in the first quadrant. The horizontal axis is labeled Company A (x) and runs from 0 to 100 (gridlines every 10); the vertical axis is labeled Company B (y) and runs from 0 to 50 (gridlines every 10). A straight line decreases from the y-intercept at (0, 40) down to the x-intercept at (60, 0).', passage='The graph shows the relationship between the number of shares of stock from Company A, $x$, and the number of shares of stock from Company B, $y$, that Simone can purchase.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=4 AND tq.number=16;
UPDATE public.test_questions tq SET figure='/data/tests/cb-og-10/figures/m4-q26.png', passage_alt='Two histograms side by side, each with a vertical axis labeled Frequency (0 to 12) and a horizontal axis labeled Integer with bin boundaries at 10, 20, 30, 40, 50, 60. Data Set A: bars over the intervals starting at 10, 20, 30, 40 with frequencies of approximately 3, 4, 7, and 9 (rising left to right). Data Set B: bars over the same intervals with the same approximate frequencies of 3, 4, 7, and 9.', passage='Two data sets of 23 integers each are summarized in the histograms shown. For each of the histograms, the first interval represents the frequency of integers greater than or equal to 10, but less than 20. The second interval represents the frequency of integers greater than or equal to 20, but less than 30, and so on.'
  FROM public.test_modules tm, public.tests t
  WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='cb-og-10' AND tm.position=4 AND tq.number=26;
