-- =============================================================================
-- Migration: 0231_dsat_italics.sql
-- Purpose:   Restore italic markup (book/work/album/film/painting/periodical
--            titles, scientific binomials, foreign-language terms) across all
--            six DSAT full tests. The scanned source PDFs have their italics
--            FLATTENED (no slant survives the digital→scan render), so the
--            transcription stored every title as plain text; spans were
--            re-derived from standard College Board typographic convention by a
--            per-test vision/convention pass (2026-06-13) and wrapped in
--            <i>…</i> (the runner renders <i> already). A few titles stored as
--            markdown *…* (which the runner does NOT render) are converted here
--            too. Idempotent: each UPDATE sets the field to its final value
--            (re-running is a no-op); word-boundary wrapping handles nested
--            titles (e.g. "I GOT UP" ⊂ "I GOT UP at 7.19 A.M. Jun 6 1977").
--            Already applied to prod via psql; this keeps the repo in sync.
--   Tooling: scripts/test-pipeline/apply-italics.py. Cosmetic — no answer impact.
-- =============================================================================
UPDATE public.test_questions tq SET passage='<i>The Skin I''m In</i> was Sharon G. Flake''s debut novel. It was published in 1998. A debut novel is the first book that an author has published. Debut novels are especially interesting to literary critics (people whose job it is to evaluate books) and readers because these books offer a look at new voices in the literary world.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-7';
UPDATE public.test_questions tq SET passage='The following text is adapted from L. M. Montgomery''s 1923 novel <i>Emily of New Moon</i>.
Emily, a young girl who lives on a farm run by her aunt Elizabeth, wants to be a published writer someday.
 One of the things they [argued] about was the fact that Emily, as Aunt Elizabeth discovered one day, was in the habit of using more of her egg money to buy paper than Aunt Elizabeth approved of. What did Emily do with so much paper? They had a fuss over this and eventually Aunt Elizabeth discovered that Emily was writing stories. Emily had been writing stories all winter under Aunt Elizabeth''s very nose and Aunt Elizabeth had never suspected it. She had fondly supposed that Emily was writing school compositions.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-8';
UPDATE public.test_questions tq SET passage='Describing adverbs as "silly," novelist Chuck Palahniuk is one of several authors and literary critics who have recommended minimizing the use of adverbs, especially those ending in <i>-ly</i> (e.g., "graciously"), in works of fiction. To investigate the prevalence of <i>-ly</i> adverbs in novels, author and statistician Ben Blatt used natural language processing—machine learning technology that reads and interprets text—to calculate the rates at which these words occur in the novels of William Faulkner, who was awarded the Nobel Prize in Literature in 1949. Blatt concluded that in Faulkner''s oeuvre, there is a negative correlation between <i>-ly</i> adverb proliferation and perceived literary merit.', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Whereas Faulkner''s acclaimed novel <i>The Sound and the Fury</i> has one of the lowest -ly adverb rates among Faulkner''s works, F. Scott Fitzgerald''s classic novel <i>The Great Gatsby</i> has the lowest -ly adverb rate among Fitzgerald''s novels.'::text)),'{B}',to_jsonb('In <i>The Sound and the Fury</i>, which is widely recognized as a literary masterpiece, Faulkner used 42 -ly adverbs per 10,000 words, whereas in his less-acclaimed novel <i>Soldiers'' Pay</i>, Faulkner used 148 -ly adverbs per 10,000 words.'::text)),'{C}',to_jsonb('In his celebrated novel <i>Light in August</i>, Faulkner used 67 -ly adverbs per 10,000 words, whereas 67% of celebrated authors'' novels that have fewer than 50 -ly adverbs per 10,000 words have been classified as great by critics.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-12';
UPDATE public.test_questions tq SET passage='Students in a biology class investigated why individual house mice (<i>Mus musculus</i>) can differ from one another in their circulating sodium level. The students compared wild-type mice and knockout mice, which are mice with specific genes deactivated, when mice of each type were placed in similar naturalistic environments and taken for periodic blood sampling. Finding that knockout mice with the gene <i>Asb5</i> deactivated tended to have lower concentrations of sodium in their blood than did wild-type mice, the students concluded that differences in circulating sodium level among house mice in nature are solely attributable to variations in the level of expression of <i>Asb5</i>.', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Some wild-type mice were very similar to the knockout mice with regard to circulating sodium level but showed a wide variety of levels of expression of <i>Asb5</i>.'::text)),'{B}',to_jsonb('A sampling of house mice captured in natural settings shows that individual mice can differ from one another in the level of expression of <i>Asb5</i>.'::text)),'{C}',to_jsonb('The level of expression of <i>Asb5</i> does not appear to affect the functioning of any other genes in house mice.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-13';
UPDATE public.test_questions tq SET choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('August 2, 1991, was when space shuttle <i>Atlantis</i> took flight with five crew members aboard.'::text)),'{B}',to_jsonb('it was August 2, 1991, when five crew members took flight aboard space shuttle <i>Atlantis</i>.'::text)),'{C}',to_jsonb('five crew members took flight aboard space shuttle <i>Atlantis</i> on August 2, 1991.'::text)),'{D}',to_jsonb('space shuttle <i>Atlantis</i> took flight on August 2, 1991, with five crew members aboard.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-16';
UPDATE public.test_questions tq SET passage='In 1991, New Jersey ______ official fossil: the <i>Hadrosaurus foulkii</i>, which is a Cretaceous period dinosaur.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-17';
UPDATE public.test_questions tq SET passage='<i>Thraxas</i> by Martin Scott, <i>Richard Matheson: Collected Stories</i> by Richard Matheson, and <i>Strange Tales</i> by Rosalie Parker are all pieces of literature that have won the prestigious World Fantasy ______ the works received the honor in the categories of novel, collection, and anthology, respectively.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-20';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• Jane is the nickname of a dinosaur fossil specimen housed at the Burpee Museum of Natural History.
• The Burpee Museum of Natural History is located in Rockford, Illinois.
• Jane is a member of the genus <i>Tyrannosaurus</i>.
• Big Mike is the nickname of a dinosaur fossil specimen housed at the Museum of the Rockies.
• The Museum of the Rockies is located in Bozeman, Montana.
• Big Mike is a member of the genus <i>Tyrannosaurus</i>.', choices=jsonb_set(choices,'{C}',to_jsonb('Big Mike is the nickname of a <i>Tyrannosaurus</i> fossil specimen housed at the Museum of the Rockies in Bozeman, Montana.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-23';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• <i>The Incarnations</i> (2015) is an epistolary novel by English author Susan Barker.
• Epistolary novels are novels written primarily as a series of fictional documents.
• These documents can be letters, journal entries, newspaper clippings, and more.
• <i>The Incarnations</i> consists primarily of letters.
• The letters are sent between a taxi driver named Wang Jun and a mysterious woman.', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Consisting primarily of letters sent between a taxi driver named Wang Jun and a mysterious woman, Susan Barker''s <i>The Incarnations</i> is an epistolary novel.'::text)),'{B}',to_jsonb('Susan Barker''s novel <i>The Incarnations</i> was published in 2015 and consists primarily of letters sent between a taxi driver named Wang Jun and a mysterious woman.'::text)),'{D}',to_jsonb('Published in 2015, <i>The Incarnations</i> is an epistolary novel by English author Susan Barker.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-24';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• <i>The Future of Nostalgia</i> is a scholarly book by literary theorist Svetlana Boym.
• The book provides a multifaceted exploration of the concept of nostalgia.
• Chapter 8 explores nostalgia and Europe''s largest shopping mall.
• Chapter 17 discusses various skeptics'' takes on the concept of nostalgia.
• In chapter 17, Boym writes, "The poethics of nostalgia combines estrangement and human solidarity, affect and reflection."', choices=jsonb_set(choices,'{B}',to_jsonb('Svetlana Boym''s <i>The Future of Nostalgia</i> provides a multifaceted exploration of the concept of nostalgia.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='1-25';
UPDATE public.test_questions tq SET passage='The 2023 anthology <i>The Big Book of Cyberpunk</i> contains 108 stories, including Fritz Leiber''s "Coming Attraction" (1950) and Erica Satifka''s "Act of Providence" (2021). With its chronological scope, it is more comprehensive than the much shorter 1986 cyberpunk anthology <i>Mirrorshades</i>, but <i>Mirrorshades</i>''s careful selection of stories makes that anthology more ______.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-4';
UPDATE public.test_questions tq SET passage='The following text is from William Carlos Williams''s 1925 creative nonfiction book <i>In the American Grain</i>. Williams is discussing how works by nineteenth-century US poet and fiction writer Edgar Allan Poe were received by American readers.

Poe must suffer by his originality. Invent that which is new, even if it be made of <u>pine from your own yard</u>, and there''s none to know what you have done. It is because there''s no name. This is the cause of Poe''s lack of recognition. He was American. He was the astounding, inconceivable growth of his locality.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-5';
UPDATE public.test_questions tq SET passage='To prevent excessive microbial growth in the closed habitat of the International Space Station, relative humidity is carefully maintained. Nonetheless, <i>Veillonella parvula</i> and other bacteria, which have the potential to damage spacecraft materials, can ______ when routine crew-member activities (e.g., handwashing) produce localized humidity conditions that exceed the specified maximum for the station overall.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-6';
UPDATE public.test_questions tq SET passage='In Tunica, an Indigenous language from the lower Mississippi Valley in what is now the United States, <i>mili</i> means "red," whereas <i>milimita</i> is used to refer to several red things. This phenomenon, in which an element of a root word is repeated, sometimes with modification, within another word that is related to the root word, is called reduplication. In this case, the entire word <i>mili</i> gets repeated in <i>milimita</i>. There are many examples of this type of reduplication in Tunica.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-7';
UPDATE public.test_questions tq SET passage='<i>The Truslow</i>, first published in 1992, is a novel in Patrick O''Brian''s Aubrey/Maturin series, which includes twenty books plus an unfinished fragment of a twenty-first. <u>Some critics have found fault with the abrupt endings of <i>The Truslow</i> and other books in the series, saying that they do not finish conclusively but arbitrarily stop.</u> But other critics argue that the books should not be thought of as discrete texts with traditional beginnings and endings but as a single incredibly long work, similar to other multivolume stories, such as Anthony Powell''s <i>A Dance to the Music of Time</i>.', choices=jsonb_set(jsonb_set(choices,'{B}',to_jsonb('It argues that the unusual structure that O''Brian uses for <i>The Truslow</i> makes it one of his least entertaining books.'::text)),'{C}',to_jsonb('It presents a reason most critics think the Aubrey/Maturin series should not have the literary renown of similar works like <i>A Dance to the Music of Time</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-8';
UPDATE public.test_questions tq SET passage='<i>Argyroxiphium caliginis</i> is among the twenty-eight species of silversword plants found only on the Hawaiian archipelago that collectively illustrate the process of adaptive radiation, or the rapid diversification of an ancestral species into different, related species. Each silversword species is physically distinct, with mature plant forms ranging from trees and shrubs to vines. However, they all descended from a common tarweed plant species, with their unique physical characteristics emerging as they adapted to the archipelago''s many specific habitats over time.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-11';
UPDATE public.test_questions tq SET passage='The bird species <i>Piculus flavigula</i> (the yellow-throated woodpecker), which forages in relatively dense vegetation, and <i>Willsonis poecilinotus</i> (the common scale-backed antbird), which forages in open areas or low density vegetation, share territory in French Guiana with <i>Thamnomanes caesius</i> (the cinereous antshrike), which emits a loud alarm call when it detects predators. Biologist Ari Martinez and colleagues, who studied the ecological community the species share, hypothesized that there is an inverse relationship between birds'' field of vision while foraging and their sensitivity to alarm calls from neighboring species.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>W. poecilinotus</i> displayed no reaction when Martinez and colleagues played <i>T. caesius</i> alarm calls, whereas <i>P. flavigula</i> displayed predator-avoidance behavior in response to the calls.'::text)),'{B}',to_jsonb('Many local bird species with similar foraging habits to those of <i>P. flavigula</i> displayed no reaction when Martinez and colleagues played <i>T. caesius</i> alarm calls, whereas <i>P. flavigula</i> displayed predator-avoidance behavior.'::text)),'{C}',to_jsonb('Some individuals of <i>W. poecilinotus</i> displayed predator-avoidance behavior when Martinez and colleagues played <i>T. caesius</i> alarm calls, whereas nearly all did when <i>P. flavigula</i> alarm calls were played.'::text)),'{D}',to_jsonb('When Martinez and colleagues played <i>T. caesius</i> alarm calls, <i>P. flavigula</i> and <i>W. poecilinotus</i> displayed no reaction, whereas <i>T. caesius</i> displayed predator-avoidance behavior.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-12';
UPDATE public.test_questions tq SET passage='To measure changes in parasite abundance over time, Chelsea Wood and colleagues counted parasite individuals preserved on specimens of striped sea perch, surf smelt, and six other fish species collected from Puget Sound between 1880 and 2019. Using statistical models to estimate historical populations, the researchers determined that for every 1°C increase in annual average sea surface temperature, the abundance of complex life cycle parasites like <i>Lecithaster sp.</i>, which require at least three host species throughout their life cycle, decreased by 38%. However, the abundance of <i>Bomolochus bellones</i> and other directly transmitted parasites, which require only one host species, was essentially unchanged. These findings suggest that ______', choices=jsonb_set(choices,'{A}',to_jsonb('<i>Lecithaster sp.</i> abundance decreased by 38% over the period studied, whereas <i>B. bellones</i> abundance did not.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-16';
UPDATE public.test_questions tq SET passage='Many paintings of the trompe l''oeil genre attain their illusory verisimilitude by depicting quotidian things, such as a fly or an empty bird cage, as if they are placed directly on top of the painted canvas. Nicola van Houbraken''s 1700 trompe l''oeil <i>Portrait of François Rivière</i>. ______ startles the viewer with the extraordinary sight of a man appearing to poke his head out from within the picture frame.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-24';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• Katrin Heer, Larissa Albrecht, and Elisabeth K. V. Kalko published a study in 2010.
• In it, the researchers found that ingestion by bats had a neutral effect on the germination of <i>Ficus nymphaefolia</i> plant seeds.
• Mikaela Marques Pulzatto and M. S. Dainez Filho published a study in 2017.
• In it, the researchers found that ingestion by bats had a negative effect on the germination of <i>Ficus luschnathiana</i> plant seeds.
• Reinaldo Chaves Teixeira, C. Corrêa, and E. Fischer published a study in 2009.
• In it, the researchers found that ingestion by bats had a positive effect on the germination of <i>Ficus pertusa</i> plant seeds.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-25';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• <i>Waiting</i> is a 1987 black-and-white linocut print by Kuwaiti artist Thuraya Al-Baqsami.
• It depicts a tranquil, everyday scene: a woman in a headscarf gazing out a window.
• <i>¡Sera toda nuestra!</i> ("It will all be ours!") is a 1977 color linocut print by Mexican American artist Carlos Cortéz.
• It features a group of laborers preparing to go on strike.
• Lino cutting is an inexpensive printmaking technique in which an image is carved onto linoleum tile, covered in ink or paint, and stamped onto paper.', choices=jsonb_set(choices,'{C}',to_jsonb('Cortéz made <i>¡Sera toda nuestra!</i> ("It will all be ours!") in 1977, while Al-Baqsami made <i>Waiting</i> later, in 1987.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-26';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• Between the fifteenth and sixteenth centuries, the city of Timbuktu was part of the Songhai Empire.
• Timbuktu was a center of trade and scholarship in the Sahara desert.
• The city was known for its hundreds of thousands of written manuscripts on both secular and religious subjects.
• The manuscripts survive today in dozens of private libraries across the city.
• <i>The Pearls Leading to Accepted Guidance</i> is one of these manuscripts.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Between the fifteenth and sixteenth centuries, the city of Timbuktu was home to <i>The Pearls Leading to Accepted Guidance</i>, a manuscript that discusses trade centers across the Sahara desert.'::text)),'{B}',to_jsonb('In the city of Timbuktu, dozens of private libraries house manuscripts, such as <i>The Pearls Leading to Accepted Guidance</i>, that discuss both secular and religious subjects.'::text)),'{C}',to_jsonb('<i>The Pearls Leading to Accepted Guidance</i> is a manuscript housed in a private library in Timbuktu.'::text)),'{D}',to_jsonb('Among Timbuktu''s vast collection of secular and religious manuscripts dating back to the Songhai Empire is <i>The Pearls Leading to Accepted Guidance</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-jun-us-c' AND tq.ref='2-27';
UPDATE public.test_questions tq SET passage='<i>Dragon against Tiger</i> is an important work of <i>Nihonga</i>, or classical Japanese painting. Unlike Wada Eisaku, who adopted traditional European methods such as painting with oil on canvas, Hashimoto Gaho ______ traditional Japanese approaches. For instance, Hashimoto produced <i>Dragon against Tiger</i> by applying color pigments to a silk surface.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-1';
UPDATE public.test_questions tq SET passage='The following text is adapted from Anton Chekhov''s 1904 play <i>The Cherry Orchard</i> (translated by Julius West in 1916).
TROFIMOV: Believe me, Anya, believe me! I''m not thirty yet, I''m young, I''m still a student, but I have undergone a great deal! I''m as hungry as the winter, I''m ill, I''m shaken... and where haven''t I been fate has tossed me everywhere!' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-3';
UPDATE public.test_questions tq SET passage='The following text is adapted from Daniel Defoe''s 1704 nonfiction book <i>The Storm</i>.
The sermon is a sound of words spoken to the ear, and prepared only for present meditation, and extends no farther than the strength of memory can convey it; a book printed is a record; remaining in every man''s possession, always ready to renew its acquaintance with his memory, and always ready to be produced as an authority or voucher to any reports he makes out of it, and conveys its contents for ages to come, to the eternity of mortal time, when the author is forgotten in his grave.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-10';
UPDATE public.test_questions tq SET passage='<i>Claudine at School</i> is a 1900 novel by Colette, originally written in French. The narrator is a fifteen-year-old girl living in a small, rural town. She presents herself as having a strong emotional attachment to the surrounding forests:______', stem='Which quotation from a translation of <i>Claudine at School</i> most effectively illustrates the claim?' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-12';
UPDATE public.test_questions tq SET passage='Veronica L. Bura, Akito Y. Kawahara, and Jayne E. Yack investigated the evolution and function of sound production in silk moth and hawk moth caterpillars. They found that during harmless simulated attacks on isolated caterpillars, 33% of the tested species produced sound, which ranged from clicks in <i>Actias luna</i> to whistles in <i>Rhodinia fugax</i>. Although some insects use sound to communicate with members of the same species, the researchers claim that the caterpillar sounds recorded in their study are directed primarily at predators.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-14';
UPDATE public.test_questions tq SET passage='Round Rock Chapter is one of the 110 chapters of the Navajo Nation (<i>Naabeehó Bináhásdzo</i>). The chapter, known as <i>Tsé Nikání</i> in the Navajo language (<i>Diné bizaad</i>), was the subject of a profile__ in the <i>Navajo Times</i> on February 13, 2014.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-17';
UPDATE public.test_questions tq SET passage='• Richard Serra is an American artist.
• He is known for his large metal sculptures.
• His large sculpture <i>Open Ended</i> is made of weathering steel.
• His large sculpture <i>Strike: To Roberta and Rudy</i> is made of hot–rolled steel.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>Open Ended</i> and <i>Strike: To Roberta and Rudy</i> are both large metal sculptures by artist Richard Serra.'::text)),'{B}',to_jsonb('<i>Strike: To Roberta and Rudy</i> is one of artist Richard Serra''s large metal sculptures.'::text)),'{C}',to_jsonb('Artist Richard Serra is the creator of the weathering steel sculpture <i>Open Ended</i>.'::text)),'{D}',to_jsonb('<i>Open Ended</i> is made from a different kind of steel than <i>Strike: To Roberta and Rudy</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-24';
UPDATE public.test_questions tq SET passage='•Maya Lin is an American artist known for her memorials and large–scale installation artworks.
• She became famous in 1982 when she completed the Vietnam Veterans Memorial, which consists of two 246–foot granite walls.
• She completed <i>Water Line</i> in 2006.
• It is an installation composed of aluminum tubing that fills an entire gallery room.
• She completed <i>Seven Earth Mountain</i> in 2015.
• It is an installation composed of soil that fills an entire gallery room.', stem='Which choice most effectively uses information from the given sentences to emphasize a difference between <i>Water Line</i> and <i>Seven Earth Mountain</i>?', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('After completing the Vietnam Veterans Memorial, Maya Lin completed <i>Water Line</i>, another large–scale work.'::text)),'{B}',to_jsonb('The sprawling size of Maya Lin''s Vietnam Veterans Memorial is echoed in <i>Water Line</i>, a work made of aluminum tubing that fills an entire gallery room.'::text)),'{C}',to_jsonb('Maya Lin''s <i>Water Line</i> is composed of aluminum tubing; <i>Seven Earth Mountain</i>, by contrast, is composed of soil.'::text)),'{D}',to_jsonb('Maya Lin is known for her memorials and installation art, such as <i>Water Line</i> and <i>Seven Earth Mountain</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='1-25';
UPDATE public.test_questions tq SET passage='In a paper for an art history class, a student claims that Rosa Bonheur''s 1855 painting <i>The Horse Fair</i> marks a significant change in Bonheur''s artistic development.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('"The paintings that Bonheur produced before <i>The Horse Fair</i> can be thought of as belonging to her earlier style, to which she never returned."'::text)),'{B}',to_jsonb('"Of all Bonheur''s paintings, none so clearly represents her abilities and ideas as <i>The Horse Fair</i>."'::text)),'{C}',to_jsonb('"<i>The Horse Fair</i> has been analyzed extensively since it was first exhibited, as no two viewers seem to agree about exactly what the painting means."'::text)),'{D}',to_jsonb('"Although Bonheur was clearly influenced by other artists of her time, she was also an artist ahead of her time, as <i>The Horse Fair</i> demonstrates."'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-9';
UPDATE public.test_questions tq SET passage='Neurobiologists Laura Cuaya, Raúl Hernández-Pérez, and colleagues investigated the language detection abilities of eighteen dogs. The researchers monitored the brain activity of Kun-kun (a border collie), Bingo (a mixed breed), and other dogs while the animals listened to three recordings: one of <i>The Little Prince</i> being read in Spanish, the second in Hungarian, and a third made up of short, randomly selected fragments of the first two, scrambled so that they didn''t resemble human speech. Each dog was familiar with either Spanish or Hungarian, but not both. The team concluded that differences in dogs anatomical features may affect their ability to distinguish speech from nonspeech.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-10';
UPDATE public.test_questions tq SET passage='<i>Cane</i> is a 1923 novel by Jean Toomer. In one portion of the novel, Toomer uses figurative language to connect the narrator''s urban environment of Washington, DC, and the rural South of the narrator''s past, writing____', stem='Which quotation from <i>Cane</i> most effectively illustrates the claim?' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-12';
UPDATE public.test_questions tq SET passage='Ships in the British Royal Navy during the Napoleonic Wars (1803-1815) were ranked based on military strength. The system considered the number of a ship''s cannons and decks. "First-rate" was the highest ranking, and "sixth-rate" was the lowest ranking, followed by unranked ships. The size of a ship''s crew was based on this ranking: first-rate ships had between 850 and 875 crewmen, while lower-ranked ships had fewer. Two of the ships in the British Royal Navy from this period were the <i>Boyne</i> (98 cannons and three decks) and the <i>Britannia</i> (120 cannons and three decks). Of these two, only the <i>Britannia</i> was ranked a first-rate ship. It can therefore be concluded that____', choices=jsonb_set(jsonb_set(choices,'{B}',to_jsonb('the <i>Britannia</i> needed a crew larger than 875 people in order to operate efficiently.'::text)),'{C}',to_jsonb('the <i>Boyne</i> had a larger crew than the <i>Britannia</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-14';
UPDATE public.test_questions tq SET passage='Long attributed to Jacques–Louis David, the preeminent Neoclassical painter of his day, the 1801 painting <i>Marie Joséphine Charlotte du Val d''Ognes</i> gained fresh attention in the 1990s when art historians discovered that the painting—which depicts a solitary young woman sketching—was actually the work of little–known French portrait __Marie–Denise Villers (1774–1821).' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-17';
UPDATE public.test_questions tq SET choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('painting <i>Gun with Hand #1</i>'::text)),'{B}',to_jsonb('painting, <i>Gun with Hand #1</i>,'::text)),'{C}',to_jsonb('painting <i>Gun with Hand #1</i>,'::text)),'{D}',to_jsonb('painting, <i>Gun with Hand #1</i>'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-18';
UPDATE public.test_questions tq SET passage='Legal scholars James Melton and Tom Ginsburg''s analysis of <i>de jure</i> judicial independence and its growth over decades__ six constitutional features that enhance such independence, including judicial tenure and selection procedure. Romania''s constitution contains one of these features.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-19';
UPDATE public.test_questions tq SET passage='Biographer Michael Gorra notes that the novelist Henry James "lived in a world of second thoughts," frequently tinkering with his novels and stories after their initial publication. However, the differences between the 1881 first edition and the 1908 edition of his novel <i>A Portrait of a Lady</i> are extreme, even by James''s standards;__ some critics regard the two editions as two different novels altogether.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-23';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• Documentary TV programs in the slow TV genre consist of uninterrupted broadcasts of ordinary events in real time.
• <i>Nordlandsbanen: Minutt for Minutt</i> is a Norwegian slow TV program.
• The 10–hour–long program documented a train ride from Trondheim to Bodø.
• It first aired in 2012.
• In her book <i>Spectacular Television: Exploring Televisual Pleasure</i>, British film scholar Helen Wheatley writes that slow TV "offers ''Unspectacular'' spectacle."', choices=jsonb_set(jsonb_set(choices,'{A}',to_jsonb('British film scholar Helen Wheatley writes about the slow TV genre in her book <i>Spectacular Television: Exploring Televisual Pleasure</i>.'::text)),'{B}',to_jsonb('An example of the slow TV genre can be seen in <i>Nordlandsbanen: Minutt for Minutt</i>, a 2012 Norwegian show featuring an uninterrupted 10–hour real–time broadcast of a train ride from Trondheim to Bodø.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-25';
UPDATE public.test_questions tq SET passage='• Calida Garcia Rawles is an African American painter.
• She is known for her large–scale, hyperrealistic paintings depicting African American figures in water.
• The painting <i>Lightness of Being</i> (24 × 30 in) depicts a young man with his arms outstretched floating on the right side of the canvas.
• <i>Lost in the Shuffle</i> (36 × 24 in) depicts two young men with their arms outstretched floating in the bottom left and upper right corners of the canvas.
• She paints the water with vivid blue colors, including periwinkle and cobalt.
• The mood in the paintings is placid.', stem='Which choice most effectively uses information from the given sentences to emphasize the location of the figures in <i>Lost in the Shuffle</i>?', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{B}',to_jsonb('In Rawles''s painting <i>Lost in the Shuffle</i>, two young men are depicted in the bottom left and upper right corners of the canvas.'::text)),'{C}',to_jsonb('At 36 by 24 inches, Rawles''s <i>Lost in the Shuffle</i> is even larger than the sizable 24–by–30–inch painting <i>Lightness of Being</i>.'::text)),'{D}',to_jsonb('Rawles captures the water in paintings such as <i>Lightness of Being</i> and <i>Lost in the Shuffle</i> in vivid hues of periwinkle and cobalt.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-26';
UPDATE public.test_questions tq SET passage='• Jean–Michel Basquiat was an American artist who produced more than two thousand drawings and paintings.
• Most of his works were completed in New York City in the 1980s.
• His work <i>Mater</i> was completed in 1982.
• The work is composed of acrylic and oil stick on canvas and measures 72 inches by 84 inches.
• <i>Mater</i> was purchased by a private collection for $5.8 million in a 2009 auction.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>Mater</i> is just one of more than two thousand drawings and paintings completed by American artist Jean–Michel Basquiat.'::text)),'{B}',to_jsonb('Though artist Jean–Michel Basquiat completed most of his two thousand–plus drawings in the 1980s, his work <i>Mater</i> is composed of acrylic and oil stick on canvas.'::text)),'{C}',to_jsonb('At a 2009 auction, artist Jean–Michel Basquiat''s <i>Mater</i>, composed of acrylic and oil stick on canvas, sold for $5.8 million.'::text)),'{D}',to_jsonb('Decades after artist Jean–Michel Basquiat completed his 1982 work <i>Mater</i>, a private collection purchased it for $5.8 million.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-nov-2023' AND tq.ref='2-27';
UPDATE public.test_questions tq SET passage='"Eyes of Zapata" is an English-language short story by Sandra Cisneros. It occasionally includes Spanish words and phrases. The English text surrounding these words and phrases ______ their meaning, so readers who aren''t familiar with Spanish can easily read the story. Ana Castillo takes the same approach in her novel <i>So Far from God</i>.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-2';
UPDATE public.test_questions tq SET passage='The following text is from Billie Jean King''s 2021 autobiography <i>All In</i>.
[P]eople on both sides of my family had repeatedly demonstrated an independent streak. In the end, that was the temperament I gravitated toward, too. Both the Moffitts and the members of my mother''s clan, the Jermans, came from mining and oil-geyser towns on the western frontier. They kept their heads down and worked, worked, worked. But they also bucked convention.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-3';
UPDATE public.test_questions tq SET passage='The dinosaur displays at museums such as the American Museum of Natural History in New York (which has a mounted <i>Allosaurus fragilis</i> skeleton among its holdings) are notable for the ______ of the research behind them—the museum staff consulted numerous sources to ensure the accuracy of the displays.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-5';
UPDATE public.test_questions tq SET passage='The Nazca lines in Peru are designs marked in the earth by ancient peoples. Monuments like these were an inspiration for the land art movement that began in the 1960s. Land art artists create works set in the outdoors. For example, in his 1968 work <i>Annual Rings</i>, Dennis Oppenheimer fashioned concentric lines that look like tree rings into the ice that covered a waterway.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-6';
UPDATE public.test_questions tq SET passage='A debut novel is the first book that an author has published. An example of a debut novel is <i>Freak the Mighty</i> by Rodman Philbrick. It was published in 1993. Debut novels are especially interesting to literary critics and readers because these books offer a look at new voices in the literary world.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-9';
UPDATE public.test_questions tq SET passage='<i>Great Expectations</i> is an 1861 novel by Charles Dickens. The narrator describes his uncle, Joe Gargery, as being both powerful and tender: ______' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-11';
UPDATE public.test_questions tq SET passage='It was long thought that maize was domesticated solely from <i>parviflumis</i> — a subspecies of teosinte, a wild grass — in Mexico''s lowlands about 9,000 years ago. However, a 2024 analysis has revealed that between 15 and 25 percent of maize''s genes can be traced to a second ______ highland subspecies of teosinte that was hybridized with maize around 4,000 years after the initial domestication.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-19';
UPDATE public.test_questions tq SET passage='Karel Čapek''s 1920 play <i>R.U.R.</i> (<i>Rossum''s Universal Robots</i>), in which artificial workers overthrow their masters, left an indelible mark on the science fiction genre, and the English language, by introducing the term "robot" (derived from the Czech word <i>robota</i>, meaning "indentured labor" or "drudgery"). ______ Čapek''s play also contributed to a venerable literary and mythological tradition: using artificial beings as mirrors and foils for humanity.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-22';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• <i>Letters from a Peruvian Woman</i> (1747) is an epistolary novel by French author Françoise de Graffigny.
• Epistolary novels are novels written primarily as a series of fictional documents.
• These documents can be letters, journal entries, newspaper clippings, and more.
• <i>Letters from a Peruvian Woman</i> consists primarily of letters.
• The letters are sent between a captured Incan princess and her fiancé.', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Published in 1747, <i>Letters from a Peruvian Woman</i> is an epistolary novel by French author Françoise de Graffigny.'::text)),'{B}',to_jsonb('Françoise de Graffigny''s novel <i>Letters from a Peruvian Woman</i> was published in 1747 and consists primarily of letters exchanged between a captured Incan princess and her fiancé.'::text)),'{C}',to_jsonb('Consisting primarily of letters exchanged between a captured Incan princess and her fiancé, Françoise de Graffigny''s <i>Letters from a Peruvian Woman</i> is an epistolary novel.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='1-23';
UPDATE public.test_questions tq SET passage='Although more documentaries are being made than ever before, too many seem ______, offering stories without any depth. In a refreshing contrast, Ahmir "Questlove" Thompson''s 2021 documentary <i>Summer of Soul (...or, When the Revolution Could Not Be Televised)</i> draws from present-day interviews to supply compelling historical and social context for footage of the 1969 Harlem Cultural Festival.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-1';
UPDATE public.test_questions tq SET passage='The following text is adapted from Edith Wharton''s 1911 novella <i>Ethan Frome</i>. The narrator has asked the woman he rents a room from about <i>Ethan Frome</i>, a town resident he encountered recently.

Her mind was a store-house of innocuous anecdote and any question about her acquaintances brought forth a volume of detail; but on the subject of <i>Ethan Frome</i> I found her unexpectedly reticent. There was no hint of disapproval in her reserve; I merely felt in her an insurmountable reluctance to speak of him.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-3';
UPDATE public.test_questions tq SET passage='Within higher education, studying philosophy requires that students be conversant with the field''s foundational texts and historical figures. By contrast, <i>doing</i> philosophy within or beyond the academy demands the creative, self-directed application of acquired expertise to enduring questions about the nature of existence and knowledge. While both approaches engage with influential figures, those who do philosophy treat such figures as vital interlocutors who facilitate new insights rather than as ossified authorities who, though relevant to the present, primarily represent the discipline''s past.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-8';
UPDATE public.test_questions tq SET passage='Now seen as a mechanical precursor to the e-reader, Spanish educator and inventor Angela Ruiz Robles''s <i>Enciclopedia Mecánica</i> eschewed pages in favor of three horizontal paper scrolls that could be easily swapped out to accommodate a range of subjects. Though Ruiz Robles''s prototype had limited functionality, interactive features described in her 1949 patent—such as a button labeled "verb" that would illuminate relevant text when pressed — ______ an impressive early vision of hypertext.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-16';
UPDATE public.test_questions tq SET passage='Jane Austen''s <i>Northanger Abbey</i> (1818) is considered a satire of another novel popular at the time: Ann Radcliffe''s <i>The Mysteries of Udolpho</i> (1794), which Austen''s heroine, Catherine Morland, is depicted reading. However, the similarity of the ______ experiences—the predicaments of both Catherine and Radcliffe''s Emily St. Aubert result from men''s greed—suggests that underlying the satire is a social critique.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-17';
UPDATE public.test_questions tq SET passage='Roger Angell''s reputation as one of the greatest baseball writers of all ______ bolstered by dozens of <i>New Yorker</i> essays in which he demonstrated a deep affection for and knowledge of the game, has perhaps overshadowed his remarkable career as a fiction editor: during his decades-long tenure at the <i>New Yorker</i>, Angell helped shape the work of John Updike, Ann Beattie, and other contributors of note.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2026-mar-asia-a' AND tq.ref='2-18';
UPDATE public.test_questions tq SET passage='Table with two rows: Right circular cylinder A has volume 392<i>pi cubic units; Right circular cylinder B has volume 10,584</i>pi cubic units.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='4-16';
UPDATE public.test_questions tq SET passage='Orbicella faveolata, a Caribbean coral with a boulder-like shape, and <i>Pocillopora eydouxi</i>, a coral from the Indian Ocean with branching clusters, are both stony corals—the type that builds reefs. Increasing stony coral colonies worldwide is a key objective for ecologists, since land-based runoff and other pressures are causing growing harm to reefs. In the wild, crustose coralline algae (CCA) promote growth in the healthy reefs they inhabit by releasing lipids and other metabolites—chemical cues that trigger coral larvae settlement. Biotechnology researcher Lina Haddad and team have developed a tool to restore those cues in damaged reefs: a gel coating infused with metabolites derived from Indian Ocean CCA. In tests with <i>Porites lutea</i>, an Indian Ocean stony coral, settlement rates rose substantially.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-13';
UPDATE public.test_questions tq SET passage='Scientists discovered a 350-million-year-old fossilized forest of <i>Calamophyton</i> trees in modern-day England. The scientists believe the emergence of these <i>Calamophyton</i> trees changed the land significantly. <u>For example, the tree roots would have greatly reduced soil erosion, and the accumulated twigs the trees shed likely created new habitats for animal life.</u>' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-4';
UPDATE public.test_questions tq SET passage='The following text is from Louise Erdrich''s 1986 novel <i>The Beet Queen</i>. The narrator discusses her relationship with her young niece, Dot, Celestine, the narrator''s sister-in-law, is Dot''s mother.

Dot and I had a mental connection, I was sure of it. I understood things about the baby that her mother could not accept.
For instance, she was never meant to be a baby. Dot was as impatient with babyhood as I. She tried at once to grow out of it.
Celestine never saw that, because she, and only she, took pleasure in Dot''s helpless softness. Only Celestine was saddened by her daughter''s fierce progress. Day by day, Dot grew stronger. In her shopping-cart stroller she exercised to exhaustion, bouncing for hours to develop her leg muscles.
1986 by Louise Erdrich' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-5';
UPDATE public.test_questions tq SET passage='Researchers who examined data from radio-tagged southern sea otters (<i>Enhydra lutris nereis</i>) identified fitness benefits gained by otters that used tools. By using fixed stones as anvils, tool-using otters gained access to high-quality, hard-shelled prey (e.g., mussels and clams) that they could usually not access through biting alone. Non-tool-using otters foraged abundant, energy-poor, easily extractable prey instead (e.g., snails). Even when easily processed prey were depleted, tool-using otters that processed mussels and clams were thus able to obtain their needed energy resources and to do so without incurring tooth damage.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-8';
UPDATE public.test_questions tq SET passage='<i>The Wonderful Wizard of Oz</i> is a 1900 novel by L. Frank Baum. In the novel, Dorothy lives in Kansas with her aunt and uncle, but she later finds herself in a land called Oz. The narrator indicates that her aunt and uncle''s house in Kansas is remote and solitary, writing that ______', stem='Which quotation from <i>The Wonderful Wizard of Oz</i> most effectively illustrates the claim?' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-12';
UPDATE public.test_questions tq SET passage='A group of primate conservationists recently began a long-term study of the effects of different conservation strategies on the northern muriqui (<i>Brachyteles hypoxanthus</i>). The species population is currently estimated to be around 1,000. It is challenging to accurately count these primates, however, which makes it difficult to tell whether the population is increasing, decreasing, or staying stable. The study may thus ______' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-14';
UPDATE public.test_questions tq SET passage='In premodern Europe, one could sail from the east coast of England to the Netherlands or France faster than one could travel by land to England''s capital, London. In that era, historian Michael Pye argues in his 2015 book <i>The Edge of the World: A Cultural History of the North Sea and the Transformation of Europe</i>, the North Sea did more to link the various peoples, cultures, and economies on ______ shores than to divide them.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-17';
UPDATE public.test_questions tq SET passage='The lack of accessible written sources is a common challenge faced by biographers of pre-nineteenth-century subjects. ______ when writing his biography of Alexander Hamilton (1755-1804), historian Ron Chernow had at his disposal Harold Syrett''s 26-volume, 19,000-document <i>Papers of Alexander Hamilton</i>.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-22';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• India Arie is an African American singer and songwriter.
• The media outlet BBC Music has described her music as a "blend of hip hop, soul and folk [that is] as subtle as it [is] inspired."
• Her acclaimed albums feature many talented musicians.
• Judeh Insel played guitar on her first studio album, <i>Acoustic Soul</i> (2001).
• Ricky Quiñones played guitar on her second studio album, <i>Voyage to India</i> (2002).', choices=jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Judeh Insel played guitar on India Arie''s first studio album, <i>Acoustic Soul</i>, which was released a year before her album <i>Voyage to India</i>.'::text)),'{C}',to_jsonb('<i>Acoustic Soul</i> and <i>Voyage to India</i>, released in 2001 and 2002, respectively, are albums by singer and songwriter India Arie.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-23';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• Grimanesa Amorós is a Peruvian American artist well known for her LED light sculptures.
• <i>Uros Island</i> (2011) is from her Uros series of works.
• It is made of smooth multicolored LED domes.
• <i>Golden Connection</i> (2013) is from her Huanchaco series of works.
• It is made of entangled blue and white LED tubes.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('Grimanesa Amorós often employs LED lights in her work, but the smooth LED domes of <i>Uros Island</i> stand in contrast to the tangled LED tubes of <i>Golden Connection</i>.'::text)),'{B}',to_jsonb('<i>Uros Island</i> and <i>Golden Connection</i> are two LED light sculptures by well-known artist Grimanesa Amorós.'::text)),'{C}',to_jsonb('In 2011, Grimanesa Amorós debuted <i>Uros Island</i>, a part of her Uros series.'::text)),'{D}',to_jsonb('Many of Grimanesa Amorós''s sculptures, like <i>Uros Island</i> and <i>Golden Connection</i>, incorporate LED lights in the form of domes or tubes.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='1-25';
UPDATE public.test_questions tq SET passage='The <i>Reckoning and Resilience</i> (2022) exhibition at Duke University''s Nasher Museum of Art in Durham, North Carolina, was curated to feature the work of thirty North Carolina artists. The included artists represent a wide variety of artistic disciplines, from painters such as Juan Logan to the sculptor Stephen Hayes. In its inclusion of many borrowed works, the exhibition is atypical for the Nasher Museum, which tends to curate its exhibitions around the permanent collection of contemporary art that it owns.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-5';
UPDATE public.test_questions tq SET passage='The following text is adapted from William Shakespeare''s 1597 play <i>The Tragedy of King Richard III</i>. Richard is reflecting on the recent arrest of his brother, the Duke of Clarence, on suspicion of treason against King Edward IV. Derby, Hastings, Buckingham, Rivers, Dorset, and Grey are also members of the English nobility.

RICHARD: I do the wrong, and first begin to brawl.
The secret mischiefs that I set [flowing]
I lay unto the grievous charge of others.
Clarence, whom I indeed have cast in darkness,
I do beweep to many simple [gullible people],
Namely, to Derby, Hastings, Buckingham;
And tell them ''tis the Queen and her allies
That stir the King against the Duke my brother.
Now they believe it, and withal whet me
To be revenged on Rivers, Dorset, Grey.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-9';
UPDATE public.test_questions tq SET passage='<i>Branching in Jurisprudential Schools</i> is one of the hundreds of thousands of manuscripts that have survived from roughly the sixteenth century to the present ______ being passed down through private libraries in the city of Timbuktu, Mali. Many of these manuscripts can be found at the Al-Wangari Manuscript Library.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-17';
UPDATE public.test_questions tq SET passage='The terms included in Barry Lopez and Debra Gwartney''s <i>Home Ground: A Guide to the American</i> ______ such as "karst," which refers to limestone terrain riddle with caves or sinkholes — illustrate the rich vocabulary used to describe the landforms of North America.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>Landscape</i>,'::text)),'{B}',to_jsonb('<i>Landscape</i>:'::text)),'{C}',to_jsonb('<i>Landscape</i> —'::text)),'{D}',to_jsonb('<i>Landscape</i>'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-18';
UPDATE public.test_questions tq SET passage='As part of his <i>I GOT UP</i> series, Japanese conceptual artist On Kawara spent over a decade — with near daily consistency — mailing postcards to friends declaring what time he got up each day, resulting in pieces such as <i>I GOT UP at 7.19 A. M. Jun 6 1977</i>. Such meticulous documentation of mundane ______ artworks that "resonate with existential, psychological and scientific implications about the time-space continuum," according to the <i>New York Times</i>, became Kawara''s life''s work.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-20';
UPDATE public.test_questions tq SET passage='For her film <i>I Am Somebody</i> (1970), a documentary about a successful months-long strike held by Black female hospital workers in Charleston, South Carolina, director Madeline Anderson chose a narrator who had participated in the ______ by allowing the narrative to be shaped by one of their own, amplified the agency and power the workers possessed.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-aug-asia-a' AND tq.ref='2-21';
UPDATE public.test_questions tq SET passage='The following text is from the 1996 novel <i>Desert Birds</i> by Elena Ruiz. A young girl is sitting in a room with her grandmother, Teresa, whose old rocking chair had previously been kept on the porch. The girl took comfort in the mere presence of the chair in the room. Comfort in its movement. It was faded by years in the sun and bent by occasional rain, and only in the last few months had Teresa decided to bring it inside with the family.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='1-1';
UPDATE public.test_questions tq SET passage='First published in 1920, Edith Wharton''s <i>The Age of Innocence</i> takes place in New York in the 1870s. In one scene, Newland Archer goes to the opera. The narrator portrays Archer''s social circle as valuing the familiar more than the new: ______', stem='Which quotation from <i>The Age of Innocence</i> most effectively supports the claim?' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='1-12';
UPDATE public.test_questions tq SET passage='Many poetry anthologies include only a single poem from each poet, but Asha K. Raman''s <i>Echoes of Contemporary Verse</i> includes generous selections from each poet. ______ Raman includes multiple poems by Olivia Chen and Marcus Redbird. This allows readers to engage with a wide range of each poet''s' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='1-23';
UPDATE public.test_questions tq SET passage='The dinosaur exhibits at museums such as the Field Museum in Chicago (which has a mounted <i>Parasaurolophus</i> skeleton among its collections) are notable for the ______ of the research behind them—the museum staff consulted numerous sources to ensure the accuracy of the displays.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-3';
UPDATE public.test_questions tq SET passage='Many models predict that as temperatures rise, North American tree populations will spread northward into habitats that are becoming newly suitable. However, forest surveys indicate that many species, such as the bur oak (<i>Quercus macrocarpa</i>) and the lodgepole pine (<i>Pinus contorta</i>), are showing migration lag—that is, they are not establishing northern populations as predicted. Research suggests that this lag is connected to reduced diversity of essential fungal partners at the northern edges of the trees'' ranges, making successful northward expansion difficult.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-6';
UPDATE public.test_questions tq SET passage='<i>Orbicella faveolata</i>, a Caribbean coral with a boulder-like shape, and <i>Pocillopora eydouxi</i>, a coral from the Indian Ocean with branching clusters, are both stony corals—the type that builds reefs. Increasing stony coral colonies worldwide is a key objective for ecologists, since land-based runoff and other pressures are causing growing harm to reefs. In the wild, crustose coralline algae (CCA) promote growth in the healthy reefs they inhabit by releasing lipids and other metabolites—chemical cues that trigger coral larvae settlement. Biotechnology researcher Lina Haddad and team have developed a tool to restore those cues in damaged reefs: a gel coating infused with metabolites derived from Indian Ocean CCA. In tests with <i>Porites lutea</i>, an Indian Ocean stony coral, settlement rates rose substantially.', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{B}',to_jsonb('Exposure to lipids and other metabolites released by CCA from Indian Ocean reefs improves settlement rates for larvae of <i>Orbicella faveolata</i> and a variety of other coral species in regions outside the Indian Ocean.'::text)),'{C}',to_jsonb('In Indian Ocean reefs, higher concentrations of lipids and other metabolites released by local CCA are linked to larger colonies of <i>Pocillopora eydouxi</i> and greater overall diversity of coral species.'::text)),'{D}',to_jsonb('When CCA are present and releasing lipids and other metabolites, larvae settlement rates improve nearly as much in damaged reefs with <i>Porites lutea</i> as they do in healthy reefs containing that coral.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-13';
UPDATE public.test_questions tq SET passage='"Golden Hours" by Clara J. Whitmore, published in the <i>Chicago Evening Post</i> in 1878, exemplifies the phenomenon of "fugitive verse," poems reprinted in newspapers and other nineteenth-century US periodicals without authorial oversight or even, in many cases, knowledge. Though poems that became fugitive verse were typical of newspaper poetry of their era in their reliance on such elements as simple rhyme schemes and everyday settings, the phenomenon of fugitive verse represents a significant departure from the dominant model of literary authorship in which a work is controlled by a single and publicly identified author. This practice, however, was accepted as routine, even by the poets affected; that it has come to seem anomalous is indicative of the fact that ______' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-15';
UPDATE public.test_questions tq SET passage='Curator Elena Martínez organized the 2026 exhibition <i>Hidden Threads: Clara Wells''s Textile Archive</i> at the Oregon Historical Museum in Portland with a twofold ______ the achievements of Wells, an innovative early-20th-century textile historian, and highlighting the museum''s extensive fabric collection.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-18';
UPDATE public.test_questions tq SET passage='Mark di Suvero''s steel sculpture <i>Schubert Sonata</i> is displayed at Millennium Park, an outdoor art space in Chicago. ______ it is exposed to rain, snow, heat, and humidity. Di Suvero''s sculpture is particularly well suited to withstand these conditions, though, because it is made of weathering steel.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-june-2026-asia' AND tq.ref='2-22';
UPDATE public.test_questions tq SET passage='The following text is from Charles Chesnutt''s 1905 novel <i>The Colonel''s Dream</i>. Mr. French and Mr. Kirby work together.

Mr. French, the senior partner, who sat opposite Kirby, was an older man—a safe guess would have placed him somewhere in the debatable ground between forty and fifty; of a good height, as could be seen even from the seated figure, the upper part of which was held erect with the unconscious ease which one associates with military training.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-4';
UPDATE public.test_questions tq SET passage='Text 1
Thomas Piketty''s book <i>Capital in the Twenty-First Century</i> has a more rigorous structure than its sequel, <i>Capital and Ideology</i>. While the first book''s chapters all contribute to bolstering a clear, coherent argument about income inequality, the second book''s digressions on subjects such as an analysis of Hayao Miyazaki''s film <i>The Wind Rises</i> do not just make the book tedious but also muddy its reasoning.

Text 2
<i>Capital and Ideology</i> has different aims than Piketty''s earlier books. It should be judged not just in the context of Piketty''s previous work but placed next to books like William T. Vollmann''s <i>Rising Up and Rising Down</i>, in which the stated theme of justifications for violent acts is mainly an excuse for a polymath to map his own mind. Even when sections do not explicitly support the central thesis, they link to each other in intriguing ways. None of them should be considered extraneous.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>Capital and Ideology</i> is notably different in structure from some of Piketty''s earlier work.'::text)),'{B}',to_jsonb('<i>Capital in the Twenty-First Century</i> is a superior book to <i>Capital and Ideology</i>.'::text)),'{C}',to_jsonb('The material in <i>Capital and Ideology</i> on <i>The Wind Rises</i> is essential to the book.'::text)),'{D}',to_jsonb('<i>Capital and Ideology</i> was influenced by the writing of William T. Vollmann.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-8';
UPDATE public.test_questions tq SET passage='Musician and astronomer Darsan Swarop Bellie researches gravitational waves. These invisible waves move very quickly through space. They cannot be viewed through a telescope, but they do make sounds that can be detected with special equipment. In his musical composition <i>Dance of the Black Holes</i>, Bellie demonstrates what gravitational waves might sound like as two black holes merge in space. With this composition and others, Bellie hopes to make aspects of science more accessible.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-9';
UPDATE public.test_questions tq SET passage='The following text is from Yung Wing''s 1909 memoir <i>My Life in China and America</i>.

We landed in New York on the 12th of April, 1847, after a passage of ninety-eight days of unprecedented fair weather. The New York of 1847 was altogether a different city from the New York of 1909. It was a city of only 250,000 or 300,000 inhabitants; now it is a metropolis rivaling London in population, wealth and commerce. The whole of Manhattan Island is turned into a city of skyscrapers, churches and palatial residences.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-11';
UPDATE public.test_questions tq SET passage='<i>Memoirs of Elleanor Eldridge</i> is an 1838 historical account by Elleanor Eldridge and Frances Harriet Whipple Green. In the book, the authors assert that all people naturally have an emotional attachment to where they live, writing ______', stem='Which quotation from <i>Memoirs of Elleanor Eldridge</i> most effectively illustrates the claim?' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-12';
UPDATE public.test_questions tq SET passage='"What stories like this do for us is make the world just a smidge bigger," writes Stephen Graham Jones in the foreword to <i>Never Whistle at Night: An Indigenous Dark Fiction Anthology</i>. For Jones, dark fiction does more than entertain readers: ______ horror tropes to challenge familiar ways of knowing, blurring the "borders of the real."' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-16';
UPDATE public.test_questions tq SET passage='Many past Olympic Games featured demonstration sports—nonmedal events—to showcase sports related to the host country. These events included <i>sumō</i>, a Japanese form of wrestling, and <i>pärkspel</i>, a Swedish ball sport. ______ they were chosen as demonstration sports at the Olympic Games in Tokyo, Japan, and Stockholm, Sweden, respectively.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-21';
UPDATE public.test_questions tq SET passage='A team led by Portuguese researcher Isabel C. F. R. Ferreira found that many species of mushrooms contain chemicals called phenolic compounds, such as protocatechuic acid and biochanin. ______ Ferreira detected protocatechuic acid in <i>Agaricus bisporus</i> mushrooms and biochanin in <i>Ganoderma lucidum</i> mushrooms.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-22';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• The willow oak is a species of deciduous tree.
• Its scientific name is <i>Quercus phellos</i>.
• It is native to the Southeastern ecoregion of the US.', choices=jsonb_set(jsonb_set(choices,'{B}',to_jsonb('The willow oak (<i>Quercus phellos</i>) is a species of deciduous tree.'::text)),'{C}',to_jsonb('The willow oak''s scientific name is <i>Quercus phellos</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-25';
UPDATE public.test_questions tq SET passage='While researching a topic, a student has taken the following notes:
• In music theory, the term "key" refers to the set of musical notes that forms the foundation of a piece of music.
• In <i>Régies de Composition</i> (1682), French composer Marc-Antoine Charpentier describes the mood of various musical keys.
• He describes the key of G major as "serious and magnificent."
• "Hero" (2001) by Enrique Iglesias is a song written in G major.', choices=jsonb_set(jsonb_set(choices,'{B}',to_jsonb('In <i>Régies de Composition</i>, Charpentier describes the mood of G major as "serious and magnificent."'::text)),'{C}',to_jsonb('In <i>Régies de Composition</i>, Charpentier describes the mood of G major.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='1-26';
UPDATE public.test_questions tq SET passage='Described in treatises mainly published between 1768 and 1950 (such as W. D. Dunton''s <i>Dunton''s Musical Shorthand</i>), musical stenography used quickly written squiggles and dots in an attempt to preserve, in printand in real time, the ______ features of live performances — those that result from impromptu deviations of performers when fidelity to an established musical score is not mandated.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-3';
UPDATE public.test_questions tq SET passage='The following text is from Edward Gibbon''s 1796 <i>Memoirs of My Life and Writings</i>. Gibbon reflects on publishing a volume of his series <i>The History of the Decline and Fall of the Roman Empire</i>.

I am at a loss how to describe the success of the work, without betraying the vanity of the writer. The first impression was exhausted in a few days; a second and third edition were scarcely adequate to the demand.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-4';
UPDATE public.test_questions tq SET passage='Harold Newton''s <i>Yellow Day</i>, a wetland landscape with palm trees and lush greenery set against the pastel yellows and pinks of the sky and water, is typical of paintings by the Florida Highwaymen, loosely affiliated landscape artists mainly active in Fort Pierce, Florida, during the 1950s and ''60s. Some art historians suggest that Highwaymen paintings played a role in shaping popular perceptions of the state that persist today: the natural iconography that Newton and colleagues constantly revisited—lush tropical forests, vivid sunsets—is now seen as classically Floridian.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-5';
UPDATE public.test_questions tq SET passage='Based on findings from fossil sites, paleobotanists had developed the so-called partition hypothesis, which holds that there were two distinctly different kinds of biomes during the Devonian period (circ a 360 to 420 million years ago). One was a tropical deltaic forest biome home to plants such as the fernlike <i>Eospermatopteris</i>, and the other was an arid floodplain forest biome home to plants such as the coniferlike <i>Archaeopteris</i>. Recently, however, evolutionary ecologist Khudadad Khudadad examined the remnants of a Devonian forest in what is now Cairo, New York, and concluded that evidence from the Cairo site is inconsistent with the partition hypothesis.

<i>Dospermatopteris</i>

and <i>Archaeopteris</i> lived there', choices=jsonb_set(jsonb_set(jsonb_set(choices,'{B}',to_jsonb('Fossil evidence from the site suggests that several forest plant species other than <i>Dospermatopteris</i> and <i>Archaeopteris</i> lived there the Devonian period.'::text)),'{C}',to_jsonb('Although the site appears to have been a tropical deltaic forest during the Devonian period, fossil evidence suggests that <i>Eospermatopteris</i> was present at that time.'::text)),'{D}',to_jsonb('The site appears to have been an arid floodplain forest during the Devonian period and contains fossil evidence of contemporaneous <i>Dospermatopteris</i> and <i>Archaeopteris</i>.'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-12';
UPDATE public.test_questions tq SET passage='Alberto Gabriele, author of <i>Reading Popular Culture in Victorian Print</i>, tracks the transnational dissemination of works by author Mary Elizabeth Braddon via the magazine______from 1866 to 1899 and distributed throughout the Australian cities of Melbourne, Adelaide, and Hobart; the continental European cities of Brussels, Paris, and Turin; and cities in Turkey, India, and Jamaica, this magazine helped make Braddon''s serialized novels globally available.', choices=jsonb_set(jsonb_set(jsonb_set(jsonb_set(choices,'{A}',to_jsonb('<i>Belgravia</i>, published'::text)),'{B}',to_jsonb('<i>Belgravia</i> published'::text)),'{C}',to_jsonb('<i>Belgravia</i>; published'::text)),'{D}',to_jsonb('<i>Belgravia</i>. Published'::text)) FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-21';
UPDATE public.test_questions tq SET passage='At Storm King Art Center, an outdoor sculpture park in New York, Herbert Ferber''s <i>Konkapot II</i> is exposed to rain, snow, heat, and humidity. ______ it remains in good condition due to its material: Ferber''s sculpture is made of corrosion-resistant steel.' FROM public.test_modules tm, public.tests t WHERE tq.module_id=tm.id AND tm.test_id=t.id AND t.slug='dsat-2025-oct-asia-a' AND tq.ref='2-24';
